### ISSUE TITLE
Attempting to save an element in an unsupported site

### ISSUE THREAD

**Issue by malamoet** [spicywebau/craft-neo#171]
Hi,

I'm getting the following error when duplicating entries (Save as a new entry).
```
yii\base\Exception: Attempting to save an element in an unsupported site. in /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/services/Elements.php:398
Stack trace:
#0 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/services/Elements.php(613): craft\services\Elements->saveElement(Object(benf\neo\elements\Block), false, false)
#1 /data/sites/web/ariadeu/apps/production/releases/52/vendor/spicyweb/craft-neo/src/services/Fields.php(226): craft\services\Elements->duplicateElement(Object(benf\neo\elements\Block), Array)
#2 /data/sites/web/ariadeu/apps/production/releases/52/vendor/spicyweb/craft-neo/src/Field.php(526): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry), true)
#3 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/base/Element.php(1841): benf\neo\Field->afterElementSave(Object(craft\elements\Entry), true)
#4 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/elements/Entry.php(1085): craft\base\Element->afterSave(true)
#5 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/services/Elements.php(498): craft\elements\Entry->afterSave(true)
#6 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/services/Elements.php(588): craft\services\Elements->saveElement(Object(craft\elements\Entry), false, false)
#7 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/controllers/EntriesController.php(499): craft\services\Elements->duplicateElement(Object(craft\elements\Entry))
#8 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#9 /data/sites/web/ariadeu/apps/production/releases/52/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /data/sites/web/ariadeu/apps/production/releases/52/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('save-entry', Array)
#12 /data/sites/web/ariadeu/apps/production/releases/52/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#13 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/save-en...', Array)
#14 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('entries/save-en...', Array)
#15 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /data/sites/web/ariadeu/apps/production/releases/52/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /data/sites/web/ariadeu/apps/production/releases/52/web/index.php(21): yii\base\Application->run()
#18 {main}

Next yii\web\ServerErrorHttpException: An error occurred when duplicating the entry. in /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/controllers/EntriesController.php:521
Stack trace:
#0 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#1 /data/sites/web/ariadeu/apps/production/releases/52/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /data/sites/web/ariadeu/apps/production/releases/52/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('save-entry', Array)
#4 /data/sites/web/ariadeu/apps/production/releases/52/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#5 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/save-en...', Array)
#6 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('entries/save-en...', Array)
#7 /data/sites/web/ariadeu/apps/production/releases/52/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /data/sites/web/ariadeu/apps/production/releases/52/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /data/sites/web/ariadeu/apps/production/releases/52/web/index.php(21): yii\base\Application->run()
#10 {main}
```
Since this error only occurs when duplicating entries **with** NEO fields, i'm guessing it has something to do with the NEO plugin?

Could any body take a look please?

Thanks,
Thomas

**Comment by ttempleton** [comment]
Thanks @brandonkelly!

@malamoet This will be fixed in Neo and released within the next day.
