### ISSUE TITLE
Problem when updating from Craft 2

### ISSUE THREAD

**Issue by justjoolz** [spicywebau/craft-neo#172]
I just updated a site to Craft 3 everything seemed to go smoothly when installing Neo but when I try to access the field page I run into an internal server error and this in the logs:

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'maxChildBlocks' in 'field list' in /var/www/site/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /var/www/site/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /var/www/site/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `id`, `f...')
#2 /var/www/site/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/site/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /var/www/site/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#5 /var/www/site/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(46): craft\db\Query->one()
#6 /var/www/site/vendor/spicyweb/craft-neo/src/elements/Block.php(222): benf\neo\services\BlockTypes->getById('5')
#7 /var/www/site/vendor/spicyweb/craft-neo/src/elements/Block.php(716): benf\neo\elements\Block->getType()
#8 /var/www/site/vendor/spicyweb/craft-neo/src/elements/Block.php(350): benf\neo\elements\Block->_getTypeHandlePrefix()
#9 /var/www/site/vendor/craftcms/cms/src/base/Element.php(782): benf\neo\elements\Block->hasEagerLoadedElements('type')
#10 /var/www/site/vendor/craftcms/cms/src/helpers/Template.php(57): craft\base\Element->__get('type')
#11 /var/www/site/storage/runtime/compiled_templates/53/534ca6c6c030bfce45fca42fbac2b184993c897d330f51b3ae068a5002bbc89e.php(57): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(benf\neo\elements\Block), 'type', Array)
#12 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_63961d602738f4a7793180f9835941d53675a4e29d69c66e9a2a97ef9f9a1b07->doDisplay(Array, Array)
#13 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#14 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#15 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#16 /var/www/site/storage/runtime/compiled_templates/bf/bf78129a7aed41c2cb3863f41c2ad74ecdba614a3c28c53dddd24f6f57ac30e4.php(103): craft\web\twig\Template->display(Array)
#17 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_43a6579c41007350b6fbb622446e694e7e6a5c08b51e68d1ceb248e364cfc6cc->block_content(Array, Array)
#18 /var/www/site/storage/runtime/compiled_templates/4c/4c83ebd8ba3468ed51ab45785640206a2cde726d139b6d5ffc9daa30ef2691c5.php(115): Twig_Template->displayBlock('content', Array, Array)
#19 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_307112e92d8d419469bca259e7565baee626a94c7a018a6acad3a1e506a68d5d->doDisplay(Array, Array)
#20 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#21 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#22 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#23 /var/www/site/storage/runtime/compiled_templates/bf/bf78129a7aed41c2cb3863f41c2ad74ecdba614a3c28c53dddd24f6f57ac30e4.php(77): craft\web\twig\Template->display(Array, Array)
#24 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_43a6579c41007350b6fbb622446e694e7e6a5c08b51e68d1ceb248e364cfc6cc->doDisplay(Array, Array)
#25 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#26 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#27 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#28 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#29 /var/www/site/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#30 /var/www/site/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('/_entry', Array)
#31 /var/www/site/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('/_entry', Array)
#32 /var/www/site/vendor/craftcms/cms/src/web/Controller.php(156): craft\web\View->renderPageTemplate('/_entry', Array)
#33 /var/www/site/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('/_entry', Array)
#34 [internal function]: craft\controllers\TemplatesController->actionRender('/_entry', Array)
#35 /var/www/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#36 /var/www/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#37 /var/www/site/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('render', Array)
#38 /var/www/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#39 /var/www/site/vendor/craftcms/cms/src/web/Application.php(284): yii\base\Module->runAction('templates/rende...', Array)
#40 /var/www/site/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#41 /var/www/site/vendor/craftcms/cms/src/web/Application.php(273): yii\web\Application->handleRequest(Object(craft\web\Request))
#42 /var/www/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#43 /var/www/site/web/index.php(21): yii\base\Application->run()
#44 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'maxChildBlocks' in 'field list'
The SQL being executed was: SELECT `id`, `fieldId`, `fieldLayoutId`, `name`, `handle`, `maxBlocks`, `maxChildBlocks`, `childBlocks`, `topLevel`, `sortOrder`
FROM `craft_neoblocktypes`
WHERE `id`='5'
ORDER BY `sortOrder`
LIMIT 1 in /var/www/site/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /var/www/site/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `id`, `f...')
#1 /var/www/site/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `id`, `f...')
#2 /var/www/site/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/site/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /var/www/site/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#5 /var/www/site/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(46): craft\db\Query->one()
#6 /var/www/site/vendor/spicyweb/craft-neo/src/elements/Block.php(222): benf\neo\services\BlockTypes->getById('5')
#7 /var/www/site/vendor/spicyweb/craft-neo/src/elements/Block.php(716): benf\neo\elements\Block->getType()
#8 /var/www/site/vendor/spicyweb/craft-neo/src/elements/Block.php(350): benf\neo\elements\Block->_getTypeHandlePrefix()
#9 /var/www/site/vendor/craftcms/cms/src/base/Element.php(782): benf\neo\elements\Block->hasEagerLoadedElements('type')
#10 /var/www/site/vendor/craftcms/cms/src/helpers/Template.php(57): craft\base\Element->__get('type')
#11 /var/www/site/storage/runtime/compiled_templates/53/534ca6c6c030bfce45fca42fbac2b184993c897d330f51b3ae068a5002bbc89e.php(57): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(benf\neo\elements\Block), 'type', Array)
#12 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_63961d602738f4a7793180f9835941d53675a4e29d69c66e9a2a97ef9f9a1b07->doDisplay(Array, Array)
#13 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#14 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#15 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#16 /var/www/site/storage/runtime/compiled_templates/bf/bf78129a7aed41c2cb3863f41c2ad74ecdba614a3c28c53dddd24f6f57ac30e4.php(103): craft\web\twig\Template->display(Array)
#17 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_43a6579c41007350b6fbb622446e694e7e6a5c08b51e68d1ceb248e364cfc6cc->block_content(Array, Array)
#18 /var/www/site/storage/runtime/compiled_templates/4c/4c83ebd8ba3468ed51ab45785640206a2cde726d139b6d5ffc9daa30ef2691c5.php(115): Twig_Template->displayBlock('content', Array, Array)
#19 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_307112e92d8d419469bca259e7565baee626a94c7a018a6acad3a1e506a68d5d->doDisplay(Array, Array)
#20 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#21 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#22 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#23 /var/www/site/storage/runtime/compiled_templates/bf/bf78129a7aed41c2cb3863f41c2ad74ecdba614a3c28c53dddd24f6f57ac30e4.php(77): craft\web\twig\Template->display(Array, Array)
#24 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_43a6579c41007350b6fbb622446e694e7e6a5c08b51e68d1ceb248e364cfc6cc->doDisplay(Array, Array)
#25 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#26 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#27 /var/www/site/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#28 /var/www/site/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#29 /var/www/site/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#30 /var/www/site/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('/_entry', Array)
#31 /var/www/site/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('/_entry', Array)
#32 /var/www/site/vendor/craftcms/cms/src/web/Controller.php(156): craft\web\View->renderPageTemplate('/_entry', Array)
#33 /var/www/site/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('/_entry', Array)
#34 [internal function]: craft\controllers\TemplatesController->actionRender('/_entry', Array)
#35 /var/www/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#36 /var/www/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#37 /var/www/site/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('render', Array)
#38 /var/www/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#39 /var/www/site/vendor/craftcms/cms/src/web/Application.php(284): yii\base\Module->runAction('templates/rende...', Array)
#40 /var/www/site/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#41 /var/www/site/vendor/craftcms/cms/src/web/Application.php(273): yii\web\Application->handleRequest(Object(craft\web\Request))
#42 /var/www/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#43 /var/www/site/web/index.php(21): yii\base\Application->run()
#44 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'maxChildBlocks' in 'field list'
)
```

**Comment by ttempleton** [comment]
Hi @justjoolz,

Can you please confirm the version of Neo you were using on your Craft 2 installation?  The `maxChildBlocks` column should definitely exist if using Neo 1.4.0 or newer.

**Comment by justjoolz** [comment]
I updated the site to Craft 2.7.4 and then all my plugins to the latest version (according to craft).
I'm using version 1.3.5 of Neo and it's not showing a new version available in the cp.

**Comment by ttempleton** [comment]
Sorry about the release feed issue; unfortunately the release feeds on existing releases of Neo for Craft 2 were broken when we released the Craft 3 version.  The only database change made to Neo for Craft 2 after 1.3.5 was adding the `maxChildBlocks` column to the `neoblocktypes` table, though, so you should be ready to use the Craft 3 version now that you've manually created the column.  If you have other sites to upgrade to Craft 3, Neo will need to be updated to [1.4.1](https://github.com/spicywebau/craft-neo/releases/tag/1.4.1) before upgrading to Craft 3.
