### ISSUE TITLE
Error when updating to Neo 2.2.0

### ISSUE THREAD

**Issue by 23d1** [spicywebau/craft-neo#180]
#### Description
Getting this fatal error any time I try to finish up the update, meaning it breaks the site (tested on multiple setups);

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'collapsed' in 'field list'
The SQL being executed was: SELECT id, collapsed
FROM neoblocks

Migration: benf\neo\migrations\m181022_123749_craft3_upgrade

Output:

> update in {{%elements}} ... done (time: 0.009s)
> update in {{%fields}} ... done (time: 0.009s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'collapsed' in 'field list'
The SQL being executed was: SELECT id, collapsed
FROM neoblocks (/customers/4/0/c/httpd.www/craft/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /customers/4/0/c/httpd.www/craft/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT id, c...')
#1 /customers/4/0/c/httpd.www/craft/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT id, c...')
#2 /customers/4/0/c/httpd.www/craft/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /customers/4/0/c/httpd.www/craft/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#5 /customers/4/0/c/httpd.www/craft/vendor/spicyweb/craft-neo/src/migrations/m181022_123749_craft3_upgrade.php(41): craft\db\Query->all()
#6 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/db/Migration.php(56): benf\neo\migrations\m181022_123749_craft3_upgrade->safeUp()
#7 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#8 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(benf\neo\migrations\m181022_123749_craft3_upgrade))
#9 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#10 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(489): craft\services\Updates->runMigrations(Array)
#11 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#12 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#13 /customers/4/0/c/httpd.www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /customers/4/0/c/httpd.www/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#16 /customers/4/0/c/httpd.www/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#17 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#18 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#19 /customers/4/0/c/httpd.www/craft/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#20 /customers/4/0/c/httpd.www/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /customers/4/0/c/httpd.www/index.php(21): yii\base\Application->run()
#22 {main}
```

#### Other information
- Neo version: 2.2.0
- Craft version: 3.1.5

**Comment by ttempleton** [comment]
Thanks for reporting this, @23d1.  I believe that this affects Neo 2 installations from pre-release, or at least from prior to October 22, when the Craft 3 upgrade migration was created.  Though the plugin's schema version was first added to Neo 2 at that time, Neo 2.2 is the first release since then that the schema version has been updated.

Neo 2.2.1 is out now, with an adjustment to the Craft 3 upgrade migration to ensure that it's actually an upgrade from the Craft 2 version (by ensuring that the `neoblocks` table has a `collapsed` column) before proceeding.
