### ISSUE TITLE
Error when trying to delete (some) blocks.

### ISSUE THREAD

**Issue by 23d1** [spicywebau/craft-neo#186]
#### Description
When trying to delete some (not all) blocks, the following error happens (stack trace);

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deletedWithOwner' in 'field list' in /var/www/html/craft/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /var/www/html/craft/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /var/www/html/craft/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('UPDATE `neobloc...')
#2 /var/www/html/craft/vendor/spicyweb/craft-neo/src/elements/Block.php(456): yii\db\Command->execute()
#3 /var/www/html/craft/vendor/craftcms/cms/src/services/Elements.php(957): benf\neo\elements\Block->beforeDelete()
#4 /var/www/html/craft/vendor/spicyweb/craft-neo/src/services/Fields.php(280): craft\services\Elements->deleteElement(Object(benf\neo\elements\Block))
#5 /var/www/html/craft/vendor/spicyweb/craft-neo/src/Field.php(570): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry), false)
#6 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(1876): benf\neo\Field->afterElementSave(Object(craft\elements\Entry), false)
#7 /var/www/html/craft/vendor/craftcms/cms/src/elements/Entry.php(1105): craft\base\Element->afterSave(false)
#8 /var/www/html/craft/vendor/craftcms/cms/src/services/Elements.php(515): craft\elements\Entry->afterSave(false)
#9 /var/www/html/craft/vendor/craftcms/cms/src/controllers/EntriesController.php(551): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#10 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#11 /var/www/html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-entry', Array)
#14 /var/www/html/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#15 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('entries/save-en...', Array)
#16 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('entries/save-en...', Array)
#17 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/html/index.php(21): yii\base\Application->run()
#20 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deletedWithOwner' in 'field list'
The SQL being executed was: UPDATE `neoblocks` SET `deletedWithOwner`=FALSE WHERE `id`='3325' in /var/www/html/craft/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /var/www/html/craft/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'UPDATE `neobloc...')
#1 /var/www/html/craft/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('UPDATE `neobloc...')
#2 /var/www/html/craft/vendor/spicyweb/craft-neo/src/elements/Block.php(456): yii\db\Command->execute()
#3 /var/www/html/craft/vendor/craftcms/cms/src/services/Elements.php(957): benf\neo\elements\Block->beforeDelete()
#4 /var/www/html/craft/vendor/spicyweb/craft-neo/src/services/Fields.php(280): craft\services\Elements->deleteElement(Object(benf\neo\elements\Block))
#5 /var/www/html/craft/vendor/spicyweb/craft-neo/src/Field.php(570): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry), false)
#6 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(1876): benf\neo\Field->afterElementSave(Object(craft\elements\Entry), false)
#7 /var/www/html/craft/vendor/craftcms/cms/src/elements/Entry.php(1105): craft\base\Element->afterSave(false)
#8 /var/www/html/craft/vendor/craftcms/cms/src/services/Elements.php(515): craft\elements\Entry->afterSave(false)
#9 /var/www/html/craft/vendor/craftcms/cms/src/controllers/EntriesController.php(551): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#10 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#11 /var/www/html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-entry', Array)
#14 /var/www/html/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#15 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('entries/save-en...', Array)
#16 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('entries/save-en...', Array)
#17 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/html/index.php(21): yii\base\Application->run()
#20 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'deletedWithOwner' in 'field list'
)
```

Edit: Seems to have been a prior failed migration, ran again and it seems to work. Will investigate further.

#### Other information
- Neo version: 2.2.2
- Craft version: 3.1.7
- Is the affected Craft installation multi-site:
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:

**Comment by 23d1** [comment]
Closing, as it seems to be resolved after getting migrations going.
