### ISSUE TITLE
Error Invalid Owner Id when disabling element on multisite after upgrade to 3.2

### ISSUE THREAD

**Issue by nitech** [spicywebau/craft-neo#237]
#### Description
I just upgraded Craft CMS to latest (3.2.8). I also upgraded all other plugins: 

Admin Bar 3.1.8.1
CKEditor 1.0.0-beta.2
CP Field Inspect 1.0.6
HTML Cache 1.0.15
Imager 2.1.10
Kint 1.0.0
Mailchimp Subscribe 3.0.0
NSM Fields 0.0.14
Navigation 1.1.13
Neo 2.3.7
Redactor 2.3.3.2
SEO 3.6.1.1
Section Fields 1.1.0
Super Table 2.2.1
Typed link field 1.0.19
oEmbed 1.1.6

I saw a message saying I should upgrade Neo and Super Tables at the same time as upgrading Craft to 3.2, but I was not really able to run all the updates before after I'd updated to Craft 3.2 (the updates to the plugins were simply not available before after - perhaps they were just updates shipped after the 3.2 Craft update).

When I select multiple entries in a section and select `Set status > Disabled for site`, I get `An unknwon error has occurred`

![image](https://user-images.githubusercontent.com/1279436/62454989-b52a0f80-b775-11e9-8f1b-2c329bed9bbf.png)

![image](https://user-images.githubusercontent.com/1279436/62455078-e4d91780-b775-11e9-81dc-1660e803973e.png)

When I then look inside web.log, I see: 

```log
019-08-05 02:40:52 [-][1][-][profile end][yii\db\Command::query] SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `entries`.`sectionId`, `entries`.`typeId`, `entries`.`authorId`, `entries`.`postDate`, `entries`.`expiryDate`, `content`.`id` AS `contentId`, `content`.`title`, `content`.`field_nominalPressure`, `content`.`field_bodyText`, `content`.`field_button`, `content`.`field_description`, `content`.`field_productDescription`, `content`.`field_personEmail`, `content`.`field_externalLink`, `content`.`field_dispersedAirVolume`, `content`.`field_cylinderVolume`, `content`.`field_groupListHeader`, `content`.`field_locationIntro`, `content`.`field_mainEmail`, `content`.`field_maxPressure`, `content`.`field_effect`, `content`.`field_locationName`, `content`.`field_personName`, `content`.`field_productName`, `content`.`field_openInNewWindow`, `content`.`field_personPhone`, `content`.`field_buttonPrimary`, `content`.`field_relatedElementsHeader`, `content`.`field_relationTypes`, `content`.`field_seo`, `content`.`field_showRelatedElements`, `content`.`field_size`, `content`.`field_slideText`, `content`.`field_videoSlideText`, `content`.`field_slideTitle`, `content`.`field_videoSlideTitle`, `content`.`field_stretch`, `content`.`field_power`, `content`.`field_db`, `content`.`field_focusItemSubtitle`, `content`.`field_heroSubtitle`, `content`.`field_subtitle`, `content`.`field_bodyIntro`, `content`.`field_featureText`, `content`.`field_storyText`, `content`.`field_bodyTitle`, `content`.`field_featureTitle`, `content`.`field_focusItemTitle`, `content`.`field_focusTitle`, `content`.`field_heroTitle`, `content`.`field_personTitle`, `content`.`field_storyTitle`, `content`.`field_embed`, `content`.`field_videoUrl`, `content`.`field_volume`, `structureelements`.`root`, `structureelements`.`lft`, `structureelements`.`rgt`, `structureelements`.`level`, `structureelements`.`structureId`, `elements`.`revisionId`, `revisions`.`sourceId` AS `revisionSourceId`, `revisions`.`creatorId` AS `revisionCreatorId`, `revisions`.`num` AS `revisionNum`, `revisions`.`notes` AS `revisionNotes`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId`
FROM `elements` `elements`
INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT *
FROM `structures`
WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL)))
INNER JOIN `revisions` `revisions` ON `revisions`.`id` = `elements`.`revisionId`
WHERE (`elements_sites`.`siteId`='1') AND (`elements`.`id`=7879) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId`=635)
ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC
LIMIT 1) `subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`)
INNER JOIN `revisions` `revisions` ON `revisions`.`id` = `elements`.`revisionId`
ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC
2019-08-05 02:40:52 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 5
2019-08-05 02:40:52 [-][1][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL5
2019-08-05 02:40:52 [-][1][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL5
2019-08-05 02:40:52 [-][1][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL5
2019-08-05 02:40:52 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 4
2019-08-05 02:40:52 [-][1][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL4
2019-08-05 02:40:52 [-][1][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL4
2019-08-05 02:40:52 [-][1][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL4
2019-08-05 02:40:52 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 3
2019-08-05 02:40:52 [-][1][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL3
2019-08-05 02:40:52 [-][1][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL3
2019-08-05 02:40:52 [-][1][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL3
2019-08-05 02:40:52 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 2
2019-08-05 02:40:52 [-][1][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL2
2019-08-05 02:40:52 [-][1][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL2
2019-08-05 02:40:52 [-][1][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL2
2019-08-05 02:40:52 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 1
2019-08-05 02:40:52 [-][1][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-08-05 02:40:52 [-][1][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-08-05 02:40:52 [-][1][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-08-05 02:40:52 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2019-08-05 02:40:52 [-][1][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 7879 in C:\client\client_automasjon_craft_hyperlane\vendor\spicyweb\craft-neo\src\elements\Block.php:265
Stack trace:
#0 C:\client\client_automasjon_craft_hyperlane\vendor\spicyweb\craft-neo\src\elements\Block.php(194): benf\neo\elements\Block->getOwner()
#1 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\helpers\ElementHelper.php(257): benf\neo\elements\Block->getSupportedSites()
#2 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\services\Elements.php(511): craft\helpers\ElementHelper::supportedSitesForElement(Object(benf\neo\elements\Block))
#3 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\services\Elements.php(997): craft\services\Elements->saveElement(Object(benf\neo\elements\Block), false, false)
#4 C:\client\client_automasjon_craft_hyperlane\vendor\spicyweb\craft-neo\src\services\Fields.php(264): craft\services\Elements->duplicateElement(Object(benf\neo\elements\Block), Array)
#5 C:\client\client_automasjon_craft_hyperlane\vendor\spicyweb\craft-neo\src\Field.php(605): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry), true)
#6 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\base\Element.php(2054): benf\neo\Field->afterElementSave(Object(craft\elements\Entry), true)
#7 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\elements\Entry.php(1208): craft\base\Element->afterSave(true)
#8 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\services\Elements.php(645): craft\elements\Entry->afterSave(true)
#9 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\services\Elements.php(943): craft\services\Elements->saveElement(Object(craft\elements\Entry), true, true)
#10 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\services\Revisions.php(167): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#11 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\elements\Entry.php(1220): craft\services\Revisions->createRevision(Object(craft\elements\Entry), '1', NULL)
#12 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\services\Elements.php(659): craft\elements\Entry->afterPropagate(false)
#13 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\elements\actions\SetStatus.php(137): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#14 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\controllers\ElementIndexesController.php(204): craft\elements\actions\SetStatus->performAction(Object(craft\elements\db\EntryQuery))
#15 [internal function]: craft\controllers\ElementIndexesController->actionPerformAction()
#16 C:\client\client_automasjon_craft_hyperlane\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#17 C:\client\client_automasjon_craft_hyperlane\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#18 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\web\Controller.php(187): yii\base\Controller->runAction('perform-action', Array)
#19 C:\client\client_automasjon_craft_hyperlane\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('perform-action', Array)
#20 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(299): yii\base\Module->runAction('element-indexes...', Array)
#21 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(566): craft\web\Application->runAction('element-indexes...', Array)
#22 C:\client\client_automasjon_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 C:\client\client_automasjon_craft_hyperlane\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 C:\client\client_automasjon_craft_hyperlane\web\index.php(21): yii\base\Application->run()
#25 {main}
```

#### Other information
- Neo version: 2.3.7
- Craft version: 3.2.8
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: No

**Comment by nitech** [comment]
Also - when editing a specific entry and deselecting "enable for x site", I am able to save and successfully disable the entry for the current site - but not when doing so from the list view - regardless of whether I select one or multiple entries.

**Comment by pvldigital** [comment]
Hi @nitech,

I'm sure this issue is related to how the blocks are being propagated. I've made changes on how neo blocks are saved and propagated in release v2.4.0.

Can you update neo and try again to see if the issue still occurs?

**Comment by nitech** [comment]
@pvldigital Thanks. This solved the issue. Awesome work!
