### ISSUE TITLE
`Array to string conversion error` when setting propagation method on section

### ISSUE THREAD

**Issue by nitech** [spicywebau/craft-neo#241]
#### Description
When I set propagation method to `Save entries to all sites enabled for this section` on a certain section type, the `Updating search indexes` seems to hang, the entries don't become available on all sites, and the following error is logged:

```
2019-08-12 01:09:21 [-][1][-][profile end][yii\db\Command::query] SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `entries`.`sectionId`, `entries`.`typeId`, `entries`.`authorId`, `entries`.`postDate`, `entries`.`expiryDate`, `content`.`id` AS `contentId`, `content`.`title`, `content`.`field_acknowledgementsLink`, `content`.`field_nominalPressure`, `content`.`field_bodyText`, `content`.`field_button`, `content`.`field_cookiesLink`, `content`.`field_description`, `content`.`field_productDescription`, `content`.`field_personEmail`, `content`.`field_externalLink`, `content`.`field_dispersedAirVolume`, `content`.`field_cylinderVolume`, `content`.`field_groupListHeader`, `content`.`field_locationIntro`, `content`.`field_mainEmail`, `content`.`field_maxPressure`, `content`.`field_moreContactInfoLink`, `content`.`field_effect`, `content`.`field_locationName`, `content`.`field_personName`, `content`.`field_productName`, `content`.`field_openInNewWindow`, `content`.`field_overskrift`, `content`.`field_personPhone`, `content`.`field_buttonPrimary`, `content`.`field_relatedElementsHeader`, `content`.`field_relationTypes`, `content`.`field_seo`, `content`.`field_showRelatedElements`, `content`.`field_size`, `content`.`field_slideText`, `content`.`field_videoSlideText`, `content`.`field_slideTitle`, `content`.`field_videoSlideTitle`, `content`.`field_stretch`, `content`.`field_power`, `content`.`field_db`, `content`.`field_focusItemSubtitle`, `content`.`field_heroSubtitle`, `content`.`field_subtitle`, `content`.`field_bodyIntro`, `content`.`field_featureText`, `content`.`field_storyText`, `content`.`field_bodyTitle`, `content`.`field_featureTitle`, `content`.`field_focusItemTitle`, `content`.`field_focusTitle`, `content`.`field_heroTitle`, `content`.`field_personTitle`, `content`.`field_storyTitle`, `content`.`field_embed`, `content`.`field_videoUrl`, `content`.`field_volume`, `structureelements`.`root`, `structureelements`.`lft`, `structureelements`.`rgt`, `structureelements`.`level`, `structureelements`.`structureId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId`
FROM `elements` `elements`
INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT *
FROM `structures`
WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL)))
INNER JOIN `relations` `relations` ON (`relations`.`targetId` = `elements`.`id`) AND ((`relations`.`sourceId`='922') AND (`relations`.`fieldId`='56')) AND ((`relations`.`sourceSiteId` IS NULL) OR (`relations`.`sourceSiteId`='1'))
WHERE (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) AND (`elements_sites`.`id` = (SELECT `elements_sites`.`id`
FROM `elements` `subElements`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subElements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `subElements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `subElements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subElements`.`id`) AND (EXISTS (SELECT *
FROM `structures`
WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL)))
INNER JOIN `relations` `relations` ON (`relations`.`targetId` = `subElements`.`id`) AND ((`relations`.`sourceId`='922') AND (`relations`.`fieldId`='56')) AND ((`relations`.`sourceSiteId` IS NULL) OR (`relations`.`sourceSiteId`='1'))
WHERE (`subElements`.`archived`=FALSE) AND (`subElements`.`dateDeleted` IS NULL) AND (`subElements`.`draftId` IS NULL) AND (`subElements`.`revisionId` IS NULL) AND (`subElements`.`id` = `elements`.`id`)
ORDER BY case when `elements_sites`.`siteId` = 1 then 0 else 1 end, `elements_sites`.`id`
LIMIT 1))
ORDER BY `relations`.`sortOrder`
LIMIT 1) `subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`)
INNER JOIN `relations` `relations` ON (`relations`.`targetId` = `elements`.`id`) AND ((`relations`.`sourceId`='922') AND (`relations`.`fieldId`='56')) AND ((`relations`.`sourceSiteId` IS NULL) OR (`relations`.`sourceSiteId`='1'))
ORDER BY `relations`.`sortOrder`
2019-08-12 01:09:21 [-][1][-][info][yii\db\Command::query] SELECT `id`, `type`, `uid`
FROM `fieldlayouts`
WHERE (`dateDeleted` IS NULL) AND (`id`=47)
LIMIT 1
2019-08-12 01:09:21 [-][1][-][profile begin][yii\db\Command::query] SELECT `id`, `type`, `uid`
FROM `fieldlayouts`
WHERE (`dateDeleted` IS NULL) AND (`id`=47)
LIMIT 1
2019-08-12 01:09:21 [-][1][-][profile end][yii\db\Command::query] SELECT `id`, `type`, `uid`
FROM `fieldlayouts`
WHERE (`dateDeleted` IS NULL) AND (`id`=47)
LIMIT 1
2019-08-12 01:09:21 [-][1][-][info][yii\db\Command::query] SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `fields`.`uid`, `fields`.`searchable`, `flf`.`layoutId`, `flf`.`tabId`, `flf`.`required`, `flf`.`sortOrder`
FROM `fields` `fields`
INNER JOIN `fieldlayoutfields` `flf` ON `flf`.`fieldId` = `fields`.`id`
INNER JOIN `fieldlayouttabs` `flt` ON `flt`.`id` = `flf`.`tabId`
WHERE `flf`.`layoutId`=47
ORDER BY `flt`.`sortOrder`, `flf`.`sortOrder`
2019-08-12 01:09:21 [-][1][-][profile begin][yii\db\Command::query] SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `fields`.`uid`, `fields`.`searchable`, `flf`.`layoutId`, `flf`.`tabId`, `flf`.`required`, `flf`.`sortOrder`
FROM `fields` `fields`
INNER JOIN `fieldlayoutfields` `flf` ON `flf`.`fieldId` = `fields`.`id`
INNER JOIN `fieldlayouttabs` `flt` ON `flt`.`id` = `flf`.`tabId`
WHERE `flf`.`layoutId`=47
ORDER BY `flt`.`sortOrder`, `flf`.`sortOrder`
2019-08-12 01:09:21 [-][1][-][profile end][yii\db\Command::query] SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `fields`.`uid`, `fields`.`searchable`, `flf`.`layoutId`, `flf`.`tabId`, `flf`.`required`, `flf`.`sortOrder`
FROM `fields` `fields`
INNER JOIN `fieldlayoutfields` `flf` ON `flf`.`fieldId` = `fields`.`id`
INNER JOIN `fieldlayouttabs` `flt` ON `flt`.`id` = `flf`.`tabId`
WHERE `flf`.`layoutId`=47
ORDER BY `flt`.`sortOrder`, `flf`.`sortOrder`
2019-08-12 01:09:21 [-][1][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in C:\customer\customer_department_craft_hyperlane\vendor\wrav\oembed\src\models\OembedModel.php:49
Stack trace:
#0 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\helpers\StringHelper.php(762): wrav\oembed\models\OembedModel->__toString()
#1 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\base\Field.php(378): craft\helpers\StringHelper::toString()
#2 C:\customer\customer_department_craft_hyperlane\vendor\spicyweb\craft-neo\src\services\Blocks.php(67): wrav\oembed\fields\OembedField->getSearchKeywords()
#3 C:\customer\customer_department_craft_hyperlane\vendor\spicyweb\craft-neo\src\Field.php(552): benf\neo\services\Blocks->getSearchKeywords()
#4 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\services\Search.php(134): benf\neo\Field->getSearchKeywords()
#5 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\queue\jobs\UpdateSearchIndex.php(55): craft\services\Search->indexElementAttributes()
#6 C:\customer\customer_department_craft_hyperlane\vendor\yiisoft\yii2-queue\src\Queue.php(214): craft\queue\jobs\UpdateSearchIndex->execute()
#7 C:\customer\customer_department_craft_hyperlane\vendor\yiisoft\yii2-queue\src\cli\Queue.php(147): craft\queue\Queue->handleMessage()
#8 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\queue\Queue.php(96): craft\queue\Queue->handleMessage()
#9 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\controllers\QueueController.php(86): craft\queue\Queue->run()
#10 C:\customer\customer_department_craft_hyperlane\vendor\yiisoft\yii2\base\InlineAction.php(57): craft\controllers\QueueController->actionRun()
#11 C:\customer\customer_department_craft_hyperlane\vendor\yiisoft\yii2\base\InlineAction.php(57): ::call_user_func_array:{C:\customer\customer_department_craft_hyperlane\vendor\yiisoft\yii2\base\InlineAction.php:57}()
#12 C:\customer\customer_department_craft_hyperlane\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams()
#13 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\web\Controller.php(187): craft\controllers\QueueController->runAction()
#14 C:\customer\customer_department_craft_hyperlane\vendor\yiisoft\yii2\base\Module.php(528): craft\controllers\QueueController->runAction()
#15 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(299): craft\web\Application->runAction()
#16 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(566): craft\web\Application->runAction()
#17 C:\customer\customer_department_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(278): craft\web\Application->_processActionRequest()
#18 C:\customer\customer_department_craft_hyperlane\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest()
#19 C:\customer\customer_department_craft_hyperlane\web\index.php(21): craft\web\Application->run()
#20 {main}
```

#### Other information
- Neo version: 2.4.2
- Craft version: 3.2.9
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: No

**Comment by nitech** [comment]
Or is this only related to wrav/oembed?

**Comment by nitech** [comment]
Don't know if this helps, but of all the jobs in queue, the following has 6 attempts: 

`O:34:"craft\queue\jobs\UpdateSearchIndex":6:{s:11:"elementType";s:20:"craft\elements\Entry";s:9:"elementId";s:3:"108";s:6:"siteId";s:1:"*";s:11:"description";N;s:30:" craft\queue\BaseJob _progress";i:0;s:35:" craft\queue\BaseJob _progressLabel";N;}`

**Comment by nitech** [comment]
I deleted all the jobs in the queue and changed the propagation method again. Now it works.

**Comment by nitech** [comment]
It is certainly related to oEmbed. Have a look at https://github.com/wrav/oembed/issues/17
