### ISSUE TITLE
Unable to find the template “_components/fieldtypes/Assets/input” with Neo and Craft 3.3.1.2

### ISSUE THREAD

**Issue by zizther** [spicywebau/craft-neo#254]
#### Description
Since upgrading to Craft 3.3.1.2 Neo is causing an error where an assets field is in a Neo block.
The error shows as `Unable to find the template “_components/fieldtypes/Assets/input”`

I have disabled Neo and the entry shows fine in the CP.

This issue is only seen in the CP, not on the frontend.
There was no issue when using Craft 3.3.01

#### Steps to reproduce
1. Create a neo block which contains an assets field
2. Assign to a section
3. Try to add/edit an entry

#### Other information
- Neo version: 2.4.5
- Craft version: 3.3.1.2
- Is the affected Craft installation multi-site: No
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
- Is eager-loading used?

**Comment by pvldigital** [comment]
Hi @zizther, I'm unable to replicate this issue. Can you send me the stack trace of it?

**Comment by zizther** [comment]
@pvldigital Thanks. Here is the stack trace.

```craft\web\twig\TemplateLoaderException: Unable to find the template “_components/fieldtypes/Assets/input”. in /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/templates/_includes/field.html:22
Stack trace:
#0 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/twig/TemplateLoader.php(78): craft\web\twig\TemplateLoader->_resolveTemplate('_components/fie...')
#1 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Environment.php(299): craft\web\twig\TemplateLoader->getCacheKey('_components/fie...')
#2 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Environment.php(381): Twig\Environment->getTemplateClass('_components/fie...')
#3 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/twig/Environment.php(44): Twig\Environment->loadTemplate('_components/fie...', NULL)
#4 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Environment.php(359): craft\web\twig\Environment->loadTemplate('_components/fie...')
#5 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Environment.php(318): Twig\Environment->load('_components/fie...')
#6 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('_components/fie...', Array)
#7 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/fields/BaseRelationField.php(488): craft\web\View->renderTemplate('_components/fie...', Array)
#8 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/fields/Assets.php(225): craft\fields\BaseRelationField->getInputHtml(Object(craft\elements\db\AssetQuery), Object(benf\neo\elements\Block))
#9 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Extension/CoreExtension.php(1485): craft\fields\Assets->getInputHtml(Object(craft\elements\db\AssetQuery), Object(benf\neo\elements\Block))
#10 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Assets), 'getInputHtml', Array, 'method', false, false)
#11 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/4a/4abfa6dfd600831526c7b3196363b980e3d650ca92536f1f10c0d75642125f85.php(98): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Assets), 'getInputHtml', Array, 'method')
#12 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a1bf255e16bf7e5375a2de936fb53c9e909d04fcaa77f8c5ac2a9db8e31efe0a->doDisplay(Array, Array)
#13 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/b9/b9f462716e6f35ba93495d6f9a8f62da06244793fba6b20bb6ac5e130773fc66.php(88): Twig\Template->display(Array)
#15 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_bc21e587edf81dbd60a40164d46fd2467b35e64e5bf3cdc4e9d4aeaa57f52f73->doDisplay(Array, Array)
#16 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#18 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#19 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#20 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('_includes/field...', Array)
#21 /Users/nathanreed/Documents/Sites/something/vendor/spicyweb/craft-neo/src/services/Blocks.php(139): craft\web\View->renderTemplate('_includes/field...', Array)
#22 /Users/nathanreed/Documents/Sites/something/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(603): benf\neo\services\Blocks->renderTabs(Object(benf\neo\elements\Block), false, 'fields[pageSecC...')
#23 /Users/nathanreed/Documents/Sites/something/vendor/spicyweb/craft-neo/src/assets/FieldAsset.php(221): benf\neo\services\BlockTypes->renderTabs(Object(benf\neo\models\BlockType), false, NULL, 1)
#24 /Users/nathanreed/Documents/Sites/something/vendor/spicyweb/craft-neo/src/assets/FieldAsset.php(103): benf\neo\assets\FieldAsset::_getBlockTypesJsSettings(Array, true, false, 1)
#25 /Users/nathanreed/Documents/Sites/something/vendor/spicyweb/craft-neo/src/Field.php(883): benf\neo\assets\FieldAsset::createInputJs(Object(benf\neo\Field), Array, false, 1)
#26 /Users/nathanreed/Documents/Sites/something/vendor/spicyweb/craft-neo/src/Field.php(352): benf\neo\Field->_getInputHtml(Array, Object(craft\elements\Entry))
#27 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Extension/CoreExtension.php(1485): benf\neo\Field->getInputHtml(Object(benf\neo\elements\db\BlockQuery), Object(craft\elements\Entry))
#28 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(benf\neo\Field), 'getInputHtml', Array, 'method', false, false)
#29 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/4a/4abfa6dfd600831526c7b3196363b980e3d650ca92536f1f10c0d75642125f85.php(98): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(benf\neo\Field), 'getInputHtml', Array, 'method')
#30 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a1bf255e16bf7e5375a2de936fb53c9e909d04fcaa77f8c5ac2a9db8e31efe0a->doDisplay(Array, Array)
#31 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#32 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/b9/b9f462716e6f35ba93495d6f9a8f62da06244793fba6b20bb6ac5e130773fc66.php(62): Twig\Template->display(Array)
#33 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_bc21e587edf81dbd60a40164d46fd2467b35e64e5bf3cdc4e9d4aeaa57f52f73->doDisplay(Array, Array)
#34 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#35 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/5d/5d9df673cf6a67cb18267a03da5adfa51095d6a6ce33fcbe70bfc50d9ae5a5ea.php(74): Twig\Template->display(Array)
#36 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_877a35da6008dec7783496a535488b00b83e1c8fdcf8626234a3306e2268487a->doDisplay(Array, Array)
#37 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#38 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/25/2518c5df7499c550ea24ebc6ae4331274b55b445fa9da3f5dc4bd40c5d9a1283.php(156): Twig\Template->display(Array)
#39 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(184): __TwigTemplate_4ce1a56b4ec26aa7f1969ccb2c0c4154fdf0c02f38b2963a8f112e56ec5cb780->block_content(Array, Array)
#40 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/07/073bc6d729d18cd15f14a0936901bab22d8f99defb51bf2fb9f1616299ce18b9.php(727): Twig\Template->displayBlock('content', Array, Array)
#41 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(184): __TwigTemplate_1a83affc21d454f148e3dfb280bb630435aebc935374b7ae746ab69d24bfff9e->block_main(Array, Array)
#42 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(147): Twig\Template->displayBlock('main', Array, Array, false)
#43 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/be/be0b42e57a38f70e29bc650b3c82562a6a4094881a83168098ee1d896e0d5c9f.php(465): Twig\Template->displayParentBlock('main', Array, Array)
#44 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(184): __TwigTemplate_8df13b17b74a0c805f74c03bc9cb744db6007b86affa16f54f985ce93de772d9->block_main(Array, Array)
#45 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/07/073bc6d729d18cd15f14a0936901bab22d8f99defb51bf2fb9f1616299ce18b9.php(576): Twig\Template->displayBlock('main', Array, Array)
#46 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(184): __TwigTemplate_1a83affc21d454f148e3dfb280bb630435aebc935374b7ae746ab69d24bfff9e->block_body(Array, Array)
#47 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/93/933f960526e832075c2df0bf0f5f0205dee382a13c5abaa9fe1c1382bb9aa1f0.php(75): Twig\Template->displayBlock('body', Array, Array)
#48 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_af75462692742531218421825577f6f704d23335266b3cfa2805949635df7b7f->doDisplay(Array, Array)
#49 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#50 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/2b/2b38500bfac7720a6f5105772fe80acbb2fab779377eae32d452c360ca1918fc.php(56): Twig\Template->display(Array, Array)
#51 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_0e13b5c4c638e0c13226ae1e38420793219d9a79685e94cc3156798860c51c7e->doDisplay(Array, Array)
#52 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#53 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/07/073bc6d729d18cd15f14a0936901bab22d8f99defb51bf2fb9f1616299ce18b9.php(118): Twig\Template->display(Array, Array)
#54 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_1a83affc21d454f148e3dfb280bb630435aebc935374b7ae746ab69d24bfff9e->doDisplay(Array, Array)
#55 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#56 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/be/be0b42e57a38f70e29bc650b3c82562a6a4094881a83168098ee1d896e0d5c9f.php(148): Twig\Template->display(Array, Array)
#57 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8df13b17b74a0c805f74c03bc9cb744db6007b86affa16f54f985ce93de772d9->doDisplay(Array, Array)
#58 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#59 /Users/nathanreed/Documents/Sites/something/storage/runtime/compiled_templates/25/2518c5df7499c550ea24ebc6ae4331274b55b445fa9da3f5dc4bd40c5d9a1283.php(120): Twig\Template->display(Array, Array)
#60 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(407): __TwigTemplate_4ce1a56b4ec26aa7f1969ccb2c0c4154fdf0c02f38b2963a8f112e56ec5cb780->doDisplay(Array, Array)
#61 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#62 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#63 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#64 /Users/nathanreed/Documents/Sites/something/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#65 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('entries/_edit', Array)
#66 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/View.php(392): craft\web\View->renderTemplate('entries/_edit', Array)
#67 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('entries/_edit', Array)
#68 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/controllers/EntriesController.php(261): craft\web\Controller->renderTemplate('entries/_edit', Array)
#69 [internal function]: craft\controllers\EntriesController->actionEditEntry(Object(craft\models\Section), 55454, NULL, NULL, Object(craft\models\Site), Object(craft\elements\Entry))
#70 /Users/nathanreed/Documents/Sites/something/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#71 /Users/nathanreed/Documents/Sites/something/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#72 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('edit-entry', Array)
#73 /Users/nathanreed/Documents/Sites/something/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#74 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entries/edit-en...', Array)
#75 /Users/nathanreed/Documents/Sites/something/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#76 /Users/nathanreed/Documents/Sites/something/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#77 /Users/nathanreed/Documents/Sites/something/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#78 /Users/nathanreed/Documents/Sites/something/web/index.php(21): yii\base\Application->run()
#79 {main}```

**Comment by zizther** [comment]
I don't know if it has anything to do with Neo having Matrix fields with Assets fields within them.

**Comment by pvldigital** [comment]
strange i've been trying to replicate and still haven't been able to, even with assets within a matrix field within neo.

is there any nonstandard fields you're using?

**Comment by zizther** [comment]
There are no special fields being used in this Neo or Matrix fields.

I am using plugins, which are listed below. I have tried disabling all of them besides Neo, but the issue remains.

Only disabling the Neo plugin allows me to see the pages with the Neo field in them without any errors. But then obviously the field and field content won't show.

I have removed the vendor folder and composer.lock to reinstall everything from scratch, but no luck there.

Plugins:

- Agent
- Amazon S3
- Cookie
- Element API
- Imager
- Retour
- SEOmatic
- Spoon

The fields in the Neo field are:

- Plain text
- Redactor
- Entries
- Lightswitch
- Dropdown
- Assets (Using the AWS S3 plugin)
- Matrix (Which contain Plain text, Redactor, Lightswitch and Assets (Using the AWS S3 plugin)).

I have looked through all the fields in the Neo field to make sure they exist, and they do.

Is there anything else I can look at or send you?

**Comment by zizther** [comment]
Some good news.
I downgraded to Craft 3.3.1.1 down from 3.3.1.2 and I don't get the error anymore.

So something in Craft 3.3.1.2 is causing the issue.

**Comment by N0ps32** [comment]
We have the same issue!

**Comment by brandonkelly** [comment]
We just released Craft 3.3.2 with a fix for this. (craftcms/cms@bdd484a674c6898d50fdb9f47b9ed2d2a2ca38b4)

**Comment by zizther** [comment]
Amazing, thanks Brandon

**Comment by pvldigital** [comment]
Ah so it was something related to craft. Good to know it’s fixed. Thanks @brandonkelly
