### ISSUE TITLE
GraphQL query issue with Gatsby (Did not fetch typename for object, unable to resolve interface.)

### ISSUE THREAD

**Issue by P233** [spicywebau/craft-neo#268]
#### Description

I am building a new site with Craft as a headless CMS and Gatsby static site generator.

In the Craft built-in GraphQL IDE, I fixed the `Schema must contain unique named types but contains multiple types named...` issue by adding the scheme checking query.

Here is a working query example: 

```graphql
{
  __schema {
    types {
      name
    }
  }
  entries(id: 155) {
    ... on featurePages_featurePages_Entry {
      featurePageContentBuilder {
        ... on featurePageContentBuilder_heroSection_BlockType {
          typeHandle
        }
        ... on featurePageContentBuilder_faqsSection_BlockType {
          typeHandle
        }
      }
    }
  }
}
```

However, when I query the same thing in Gatsby GraphQL IDE, I got an error message `Did not fetch typename for object, unable to resolve interface.`

Here is my query in the Gatsby GraphQL IDE: 

```graphql
{
  __schema {
    types {
      name
    }
  }
  craft {
    entries(id: 155) {
      ... on craft_featurePages_featurePages_Entry {
        featurePageContentBuilder {
          ... on craft_featurePageContentBuilder_heroSection_BlockType {
            typeHandle
          }
          ... on craft_featurePageContentBuilder_faqsSection_BlockType {
            typeHandle
          }
        }
      }
    }
  }
}
```

The `craft_` is a prefix, please see https://www.gatsbyjs.org/docs/third-party-graphql/

Adding the scheme checking query doesn't fix this issue. I am not sure if this is the right place to ask for help, but if I remove the scheme checking query from the Craft built-in GraphQL IDE, the outputs from the two GraphQL IDEs are pretty similar.

Would you mind to have a quick look and give me some clues? Thank you!

#### Steps to reproduce
1.
2.
3.

#### Other information
- Neo version: 3.3.6
- Craft version: 2.5.2
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: Yes
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: "Only save blocks to the site they were created in"
- Is eager-loading used? No

**Comment by P233** [comment]
Here is the error message from the Gatsby GraphQL IDE: 

```json
{
  "errors": [
    {
      "message": "Did not fetch typename for object, unable to resolve interface.",
      "locations": [
        {
          "line": 10,
          "column": 9
        }
      ],
      "path": [
        "craft",
        "entries",
        0,
        "featurePageContentBuilder",
        0
      ],
      "stack": [
        "Error: Did not fetch typename for object, unable to resolve interface.",
        "    at Object.resolveFromParentTypename [as default] (project/node_modules/graphql-tools/dist/stitching/resolveFromParentTypename.js:7:15)",
        "    at graphql_1.GraphQLUnionType.resolveType (project/node_modules/graphql-tools/dist/stitching/schemaRecreation.js:47:63)",
        "    at completeAbstractValue (project/node_modules/graphql/execution/execute.js:652:21)",
        "    at completeValue (project/node_modules/graphql/execution/execute.js:585:12)",
        "    at completeValueCatchingError (project/node_modules/graphql/execution/execute.js:495:19)",
        "    at project/node_modules/graphql/execution/execute.js:618:25",
        "    at Array.forEach (<anonymous>)",
        "    at forEach (project/node_modules/iterall/index.js:83:25)",
        "    at completeListValue (project/node_modules/graphql/execution/execute.js:614:24)",
        "    at completeValue (project/node_modules/graphql/execution/execute.js:573:12)",
        "    at completeValueCatchingError (project/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (project/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (project/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (project/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (project/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeAbstractValue (project/node_modules/graphql/execution/execute.js:660:10)"
      ]
    }
  ],
  "data": {
    "__schema": {
      "types": [
        ...
      ]
   },
    "craft": {
      "entries": [
        {
          "featurePageContentBuilder": [
            null,
            {
              "typeHandle": "faqsSection"
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by pvldigital** [comment]
Hi @P233,

It could be something related to this: 
https://github.com/apollographql/graphql-tools/issues/441#issuecomment-345423403

Can you try the fix above and see if it works for you?

**Comment by P233** [comment]
@pvldigital Thank you! I tested it, but that's not working. 

Maybe this issue is not related to craft-neo. I'll close it and see if I could find any solution.

**Comment by P233** [comment]
@pvldigital Downgrading Craft to version `3.3.2` solves this issue. It is probably a bug of Craft.
