### ISSUE TITLE
Field Labels uid undefined index on project config sync

### ISSUE THREAD

**Issue by icreatestuff** [spicywebau/craft-neo#287]
#### Description
When syncing project config to a staging environment we are hit with a fatal error during the syncing process. Digging into the logs we see it's related to `Undefined index: 05929d77-08e5-4793-a521-b6c5f1500122 in /var/www/vhosts/mysite.dev/vendor/spicyweb/craft-neo/src/integrations/fieldlabels/FieldLabels.php:50`

To test we exported the database from the staging environment to use locally, ran `./craft project-config/rebuild` so local and staging DB's are identical, and the project config is fully up to date. Then we made a simple change to one field thereby updating the local project.yaml file. We deployed that file and we still hit the error during the sync.

#### Steps to reproduce
1. Install Neo & Field Labels
2. Create a Neo field and add one ore more fields that are relabeled
3. Deploy to another environment

#### Other information
- Neo version: 2.5.8
- Field Labels version: 1.1.8
- Craft version: 3.3.17
- PHP version: 

### Stack Trace
```
2019-12-10 16:20:01 [-][1][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: 05929d77-08e5-4793-a521-b6c5f1500122 in /var/www/vhosts/mysite.dev/vendor/spicyweb/craft-neo/src/integrations/fieldlabels/FieldLabels.php:50
Stack trace:
#0 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 50)
#1 /var/www/vhosts/mysite.dev/vendor/spicyweb/craft-neo/src/integrations/fieldlabels/FieldLabels.php(50): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 50, Array)
#2 [internal function]: benf\neo\integrations\fieldlabels\FieldLabels->benf\neo\integrations\fieldlabels\{closure}(Object(benf\neo\events\BlockTypeEvent))
#3 /var/www/vhosts/mysite.dev/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(benf\neo\events\BlockTypeEvent))
#4 /var/www/vhosts/mysite.dev/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('benf\\neo\\servic...', 'afterSaveNeoBlo...', Object(benf\neo\events\BlockTypeEvent))
#5 /var/www/vhosts/mysite.dev/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(442): yii\base\Component->trigger('afterSaveNeoBlo...', Object(benf\neo\events\BlockTypeEvent))
#6 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/services/ProjectConfig.php(872): benf\neo\services\BlockTypes->handleChangedBlockType(Object(benf\neo\events\BlockTypeEvent))
#7 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#8 /var/www/vhosts/mysite.dev/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#9 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/services/ProjectConfig.php(551): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#10 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/services/ProjectConfig.php(866): craft\services\ProjectConfig->processConfigChanges('neoBlockTypes.0...')
#11 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#12 /var/www/vhosts/mysite.dev/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#13 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/services/ProjectConfig.php(551): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#14 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/services/ProjectConfig.php(957): craft\services\ProjectConfig->processConfigChanges('neoBlockTypes.0...')
#15 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/services/ProjectConfig.php(441): craft\services\ProjectConfig->_applyChanges(Array)
#16 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/controllers/ConfigSyncController.php(58): craft\services\ProjectConfig->applyYamlChanges()
#17 [internal function]: craft\controllers\ConfigSyncController->actionApplyYamlChanges()
#18 /var/www/vhosts/mysite.dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /var/www/vhosts/mysite.dev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#20 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('apply-yaml-chan...', Array)
#21 /var/www/vhosts/mysite.dev/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('apply-yaml-chan...', Array)
#22 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('config-sync/app...', Array)
#23 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/web/Application.php(691): craft\web\Application->runAction('config-sync/app...')
#24 /var/www/vhosts/mysite.dev/vendor/craftcms/cms/src/web/Application.php(256): craft\web\Application->_processConfigSyncLogic(Object(craft\web\Request))
#25 /var/www/vhosts/mysite.deve/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /var/www/vhosts/mysite.dev/web/index.php(21): yii\base\Application->run()
#27 {main}
```

**Comment by pvldigital** [comment]
Hi @icreatestuff,

I think the issue is related to a fix I made for field labels, i'll need to upgrade the integration of it.

**Comment by icreatestuff** [comment]
Amazing thank you @pvldigital. Any idea when that fix will be released as an update?

**Comment by pvldigital** [comment]
@icreatestuff i'll be releasing the update today some time, just looking into some other issues first.
