### ISSUE TITLE
Craft 3.4: Integrity constraint violation when deleting entry with Neo blocks

### ISSUE THREAD

**Issue by Mosnar** [spicywebau/craft-neo#293]
#### Description
Deleting an entry with a Neo block results in the following error:
```

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`<SNIP>_production`.`craft_neoblockstructures`, CONSTRAINT `craft_neoblockstructures_ownerSiteId_fk` FOREIGN KEY (`ownerSiteId`) REFERENCES `craft_sites` (`id`) ON DELETE CASCADE ON UPDATE CASC) in /home/forge/<SNIP>/vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->execute()
#3 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('{{%neoblockstru...', Array)
#4 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#6 /home/forge/<SNIP>/vendor/spicyweb/craft-neo/src/services/Blocks.php(247): yii\db\BaseActiveRecord->save(false)
#7 /home/forge/<SNIP>/vendor/spicyweb/craft-neo/src/Field.php(760): benf\neo\services\Blocks->saveStructure(Object(benf\neo\models\BlockStructure))
#8 /home/forge/<SNIP>/vendor/craftcms/cms/src/base/Element.php(2564): benf\neo\Field->beforeElementDelete(Object(craft\elements\Entry))
#9 /home/forge/<SNIP>/vendor/craftcms/cms/src/elements/Entry.php(1279): craft\base\Element->beforeDelete()
#10 /home/forge/<SNIP>/vendor/craftcms/cms/src/services/Elements.php(1201): craft\elements\Entry->beforeDelete()
#11 /home/forge/<SNIP>/vendor/craftcms/cms/src/controllers/EntriesController.php(449): craft\services\Elements->deleteElement(Object(craft\elements\Entry))
#12 [internal function]: craft\controllers\EntriesController->actionDeleteEntry()
#13 /home/forge/<SNIP>/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /home/forge/<SNIP>/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /home/forge/<SNIP>/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('delete-entry', Array)
#16 /home/forge/<SNIP>/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-entry', Array)
#17 /home/forge/<SNIP>/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('entries/delete-...', Array)
#18 /home/forge/<SNIP>/vendor/craftcms/cms/src/web/Application.php(558): craft\web\Application->runAction('entries/delete-...', Array)
#19 /home/forge/<SNIP>/vendor/craftcms/cms/src/web/Application.php(269): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /home/forge/<SNIP>/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /home/forge/<SNIP>/web/index.php(17): yii\base\Application->run()
#22 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`<SNIP>_production`.`craft_neoblockstructures`, CONSTRAINT `craft_neoblockstructures_ownerSiteId_fk` FOREIGN KEY (`ownerSiteId`) REFERENCES `craft_sites` (`id`) ON DELETE CASCADE ON UPDATE CASC)
The SQL being executed was: INSERT INTO `craft_neoblockstructures` (`structureId`, `ownerId`, `ownerSiteId`, `fieldId`, `dateCreated`, `dateUpdated`, `uid`) VALUES (7722, 23194, 0, 41, '2020-01-28 13:32:50', '2020-01-28 13:32:50', '3883ca98-d67c-436f-bee9-fede1c8f229b') in /home/forge/<SNIP>/vendor/yiisoft/yii2/db/Schema.php:674
Stack trace:
#0 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `cr...')
#1 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->execute()
#3 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('{{%neoblockstru...', Array)
#4 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 /home/forge/<SNIP>/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#6 /home/forge/<SNIP>/vendor/spicyweb/craft-neo/src/services/Blocks.php(247): yii\db\BaseActiveRecord->save(false)
#7 /home/forge/<SNIP>/vendor/spicyweb/craft-neo/src/Field.php(760): benf\neo\services\Blocks->saveStructure(Object(benf\neo\models\BlockStructure))
#8 /home/forge/<SNIP>/vendor/craftcms/cms/src/base/Element.php(2564): benf\neo\Field->beforeElementDelete(Object(craft\elements\Entry))
#9 /home/forge/<SNIP>/vendor/craftcms/cms/src/elements/Entry.php(1279): craft\base\Element->beforeDelete()
#10 /home/forge/<SNIP>/vendor/craftcms/cms/src/services/Elements.php(1201): craft\elements\Entry->beforeDelete()
#11 /home/forge/<SNIP>/vendor/craftcms/cms/src/controllers/EntriesController.php(449): craft\services\Elements->deleteElement(Object(craft\elements\Entry))
#12 [internal function]: craft\controllers\EntriesController->actionDeleteEntry()
#13 /home/forge/<SNIP>/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /home/forge/<SNIP>/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /home/forge/<SNIP>/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('delete-entry', Array)
#16 /home/forge/<SNIP>/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-entry', Array)
#17 /home/forge/<SNIP>/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('entries/delete-...', Array)
#18 /home/forge/<SNIP>/vendor/craftcms/cms/src/web/Application.php(558): craft\web\Application->runAction('entries/delete-...', Array)
#19 /home/forge/<SNIP>/vendor/craftcms/cms/src/web/Application.php(269): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /home/forge/<SNIP>/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /home/forge/<SNIP>/web/index.php(17): yii\base\Application->run()
#22 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1452
    [2] => Cannot add or update a child row: a foreign key constraint fails (`<SNIP>_production`.`craft_neoblockstructures`, CONSTRAINT `craft_neoblockstructures_ownerSiteId_fk` FOREIGN KEY (`ownerSiteId`) REFERENCES `craft_sites` (`id`) ON DELETE CASCADE ON UPDATE CASC)
)
```

#### Steps to reproduce
1. Attempt to delete an entry with a single Neo field and blcoks

#### Other information
- Site was originally migrated with Neo fields from Craft 2
- Neo version: 2.5.10
- Craft version: 3.4-dev
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
N/A
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
N/A
- Is eager-loading used?
N/A

**Comment by pvldigital** [comment]
Hi @Mosnar,

I just made a release for Craft 3.4.0, can you update and see if the issues continue? I've tried replicating but was unsuccessful.

**Comment by Mosnar** [comment]
@pvldigital Thanks for looking at it! Still seems to be broken on one particular entry. I suspect something must be corrupted in the database - how that happened is anyone's guess. Fortunately, it seems to be a one-off, so I'm fine deleting the element data from the database manually. If you're comfortable with it, I'm comfortable with closing the issue.

**Comment by Mosnar** [comment]
**Update:** so it turns out, somehow there were a bunch of entries in my craft_neoblockstructures with null `ownerSiteId` values. Most of these were quite old, so I would assume they were from the Craft 2 site. I ran a quick update:
`UPDATE craft_neoblockstructures SET ownerSiteId = 1;`

and was able to delete the entry again!

**Comment by pvldigital** [comment]
@Mosnar oh, good to know you got it working.

It must've been an issue with the migration process from craft 2. I'll need to make sure the site id must be at least 1 (the default primary site) when saving the record.
