### ISSUE TITLE
Failure when updating from Craft 3.3 to 3.4 with unpublished drafts

### ISSUE THREAD

**Issue by OscarBarrett** [spicywebau/craft-neo#297]
#### Description
Upgrading from the following:
- Craft 3.3.18.1 -> 3.4.5
- Neo 2.5.8 -> 2.6.1

We get the following exception.
```
Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '45732' for key 'PRIMARY'
The SQL being executed was: INSERT INTO neoblocks (id, fieldId, ownerId, typeId, dateCreated, dateUpdated, uid) VALUES (45732, 10, 45731, 1, '2020-02-17 02:01:06', '2020-02-17 02:01:06', 'dcba4084-9663-4421-b0b9-4968984c5ff6')

Migration: craft\migrations\m190913_152146_update_preview_targets

Output:

Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '45732' for key 'PRIMARY'
The SQL being executed was: INSERT INTO neoblocks (id, fieldId, ownerId, typeId, dateCreated, dateUpdated, uid) VALUES (45732, 10, 45731, 1, '2020-02-17 02:01:06', '2020-02-17 02:01:06', 'dcba4084-9663-4421-b0b9-4968984c5ff6') (/app/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO ne...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO ne...')
#2 /app/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->execute()
#3 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('{{%neoblocks}}', Array)
#4 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#6 /app/vendor/spicyweb/craft-neo/src/elements/Block.php(490): yii\db\BaseActiveRecord->save(false)
#7 /app/vendor/craftcms/cms/src/services/Elements.php(2117): benf\neo\elements\Block->afterSave(true)
#8 /app/vendor/craftcms/cms/src/services/Elements.php(773): craft\services\Elements->_saveElementInternal(Object(benf\neo\elements\Block), false, false)
#9 /app/vendor/spicyweb/craft-neo/src/services/Fields.php(332): craft\services\Elements->duplicateElement(Object(benf\neo\elements\Block), Array)
#10 /app/vendor/spicyweb/craft-neo/src/Field.php(668): benf\neo\services\Fields->duplicateBlocks(Object(benf\neo\Field), Object(craft\elements\Entry), Object(craft\elements\Entry), true)
#11 /app/vendor/craftcms/cms/src/base/Element.php(2552): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), true)
#12 /app/vendor/craftcms/cms/src/elements/Entry.php(1269): craft\base\Element->afterPropagate(true)
#13 /app/vendor/craftcms/cms/src/services/Elements.php(845): craft\elements\Entry->afterPropagate(true)
#14 /app/vendor/craftcms/cms/src/services/Revisions.php(160): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#15 /app/vendor/craftcms/cms/src/elements/Entry.php(1273): craft\services\Revisions->createRevision(Object(craft\elements\Entry), NULL, NULL)
#16 /app/vendor/craftcms/cms/src/services/Elements.php(2137): craft\elements\Entry->afterPropagate(false)
#17 /app/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#18 /app/vendor/craftcms/cms/src/services/Sections.php(1545): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#19 /app/vendor/craftcms/cms/src/services/Sections.php(755): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section), Array)
#20 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1084): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#21 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#22 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#23 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(658): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#24 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1074): craft\services\ProjectConfig->processConfigChanges('sections.bc3ae7...')
#25 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#26 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#27 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(655): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#28 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(478): craft\services\ProjectConfig->processConfigChanges('sections.bc3ae7...', true, '')
#29 /app/vendor/craftcms/cms/src/migrations/m190913_152146_update_preview_targets.php(54): craft\services\ProjectConfig->set('sections.bc3ae7...', Array)
#30 /app/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m190913_152146_update_preview_targets->safeUp()
#31 /app/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#32 /app/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190913_152146_update_preview_targets))
#33 /app/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#34 /app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#35 /app/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#36 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#37 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#38 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#39 /app/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#40 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#41 /app/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('updater/migrate', Array)
#42 /app/vendor/craftcms/cms/src/web/Application.php(645): craft\web\Application->runAction('updater/migrate')
#43 /app/vendor/craftcms/cms/src/web/Application.php(222): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#44 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#45 /app/web/index.php(21): yii\base\Application->run()
#46 {main}
```

If we manually delete the block with the referenced primary ID then the upgrade completes successfully.

The owning entry appears to be an unpublished draft, so my guess would be it's some issue to do with that where Neo thinks that it needs to duplicate the block even though it already exists.

#### Other information
- Neo version: 2.6.1
- Craft version: 3.4.5
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: N/A
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: N/A
- Is eager-loading used? No

**Comment by pvldigital** [comment]
Hi @OscarBarrett,

Thanks for the report. I'll work on a fix for future updates.

**Comment by pvldigital** [comment]
Quick question, is this happening when you used composer to update or was it in the control panel? @OscarBarrett

**Comment by OscarBarrett** [comment]
The packages were updated using composer, and the update was triggered via the manual update notification that takes over the CP.

**Comment by pvldigital** [comment]
Ah really? that's strange, I wasn't able to trigger the issue using that method.

**Comment by OscarBarrett** [comment]
I'll try and set up a minimal reproduction from our affected project/db - do you have an email address that I could send files through to?

**Comment by pvldigital** [comment]
sure. you can send it to plugins@spicyweb.com.au

**Comment by OscarBarrett** [comment]
Unfortunately I haven't been able to create a simple reproduction yet.

But I have lookied further into it. The affected entry was an unsaved draft ("First draft", not visible in the CMS at all), with all but one neoblocks deleted. The one neoblock not deleted is the id mentioned in the exception.

Other specifics that seem to lead to this issue:
- There is a Single that also includes same Neo field in its Field Layout.
- Craft tries to ensure that the Single only has one entry during the update.

Going through the stack trace (since tested with Craft 3.4.9 and Neo 2.6.4):
- During the update, Craft calls [craft\services\Sections->_ensureSingleEntry](https://github.com/craftcms/cms/blob/3.4.9/src/services/Sections.php#L1514). This triggers a resave on the Single that also uses the same Neo field. It looks like this only happens when the [m190913_152146_update_preview_targets](https://github.com/craftcms/cms/blob/14c9857cf7b3fe27fb798a90ed507a8ea08cb7e6/src/migrations/m190913_152146_update_preview_targets.php#L14) Craft migration marks it as dirty due to not having a preview target or a primary page target.
- [benf\neo\services\Fields->duplicateBlocks](https://github.com/spicywebau/craft-neo/blob/master/src/services/Fields.php#L310) is eventually called due to propagation on the Single. It tries to duplicate all blocks for the Neo field that is used on both the Single and the Section that the unsaved draft belongs to.
- [craft\services\Elements->_saveElementInternal](https://github.com/craftcms/cms/blob/3.4.9/src/services/Elements.php#L2143) is called on the Neo block that belongs to the unsaved draft. This initially happens with `$isNewElement` set to false
- This triggers [craft\elements\Entry->afterPropagate](https://github.com/craftcms/cms/blob/3.4.9/src/elements/Entry.php#L1278) which attempts to create a new revision, not passing in any new attributes.
- [craft\services\Revision->createRevision](https://github.com/craftcms/cms/blob/3.4.9/src/services/Revisions.php#L160) then attempts to duplicate the element.
- [craft\services\Element->duplicateElement](https://github.com/craftcms/cms/blob/3.4.9/src/services/Elements.php#L851) calls `afterPropagate` on the clone with `$isNew` set to true as `$newAttributes['id']` is empty.
- Eventually this flows down to [benf\neo\elements\Block->afterSave](https://github.com/spicywebau/craft-neo/blob/4ec700608ac9796abe2fce5c141960729c160951/src/elements/Block.php#L467) which trusts the `$isNew` value, and tries to create a Block record, but reuses the existing ID.

So it looks like the issue happens when a Neo block is to be duplicated, but Neo's `afterSave` function on `Block` reuses the id when `$isNew` is true.

**Comment by pvldigital** [comment]
Hi @OscarBarrett,

Thanks for the detailed analysis. I'll have a more in-depth look and see if I can get it resolved.
