### ISSUE TITLE
Fails on Dashboard

### ISSUE THREAD

**Issue by gglnx** [spicywebau/craft-neo#304]
#### Description

If you using elements with Neo blocks in the Quick Post dashboard widget, starting with the last update (related to this commit: https://github.com/spicywebau/craft-neo/commit/8c95f71a1b5e71ce9fa4534aafdce0700029e285), the dashboards fails with an exception. 

```
Error: Call to a member function getId() on null
#26 /var/www/spdplus/releases/150/vendor/spicyweb/craft-neo/src/Field.php(895): _getInputHtml
#25 /var/www/spdplus/releases/150/vendor/spicyweb/craft-neo/src/Field.php(346): getInputHtml
#24 /var/www/spdplus/releases/150/vendor/twig/twig/src/Extension/CoreExtension.php(1499): twig_get_attribute
#23 /var/www/spdplus/releases/150/vendor/craftcms/cms/src/helpers/Template.php(96): attribute
#22 /var/www/spdplus/releases/150/storage/runtime/compiled_templates/18/18ae2eb194caa53fd5f532070507f2120c335ca5ad023bb118a070787a5394e7.php(87): doDisplay
#21 /var/www/spdplus/releases/150/vendor/twig/twig/src/Template.php(407): displayWithErrorHandling
#20 /var/www/spdplus/releases/150/vendor/twig/twig/src/Template.php(380): display
#19 /var/www/spdplus/releases/150/storage/runtime/compiled_templates/37/378850829a8a2626a58b6e35f40b6b0893adadd929d25fd72c4cf3f9141cb97d.php(86): doDisplay
#18 /var/www/spdplus/releases/150/vendor/twig/twig/src/Template.php(407): displayWithErrorHandling
#17 /var/www/spdplus/releases/150/vendor/twig/twig/src/Template.php(380): display
#16 /var/www/spdplus/releases/150/vendor/twig/twig/src/Template.php(392): render
#15 /var/www/spdplus/releases/150/vendor/twig/twig/src/TemplateWrapper.php(45): render
#14 /var/www/spdplus/releases/150/vendor/twig/twig/src/Environment.php(318): render
#13 /var/www/spdplus/releases/150/vendor/craftcms/cms/src/web/View.php(397): renderTemplate
#12 /var/www/spdplus/releases/150/vendor/craftcms/cms/src/widgets/QuickPost.php(168): getBodyHtml
#11 /var/www/spdplus/releases/150/vendor/craftcms/cms/src/controllers/DashboardController.php(508): _getWidgetInfo
#10 /var/www/spdplus/releases/150/vendor/craftcms/cms/src/controllers/DashboardController.php(96): actionIndex
#9 /var/www/spdplus/releases/150/vendor/craftcms/cms/src/controllers/DashboardController.php(0): call_user_func_array
#8 /var/www/spdplus/releases/150/vendor/yiisoft/yii2/base/InlineAction.php(57): runWithParams
#7 /var/www/spdplus/releases/150/vendor/yiisoft/yii2/base/Controller.php(157): runAction
#6 /var/www/spdplus/releases/150/vendor/craftcms/cms/src/web/Controller.php(178): runAction
#5 /var/www/spdplus/releases/150/vendor/yiisoft/yii2/base/Module.php(528): runAction
#4 /var/www/spdplus/releases/150/vendor/craftcms/cms/src/web/Application.php(291): runAction
#3 /var/www/spdplus/releases/150/vendor/yiisoft/yii2/web/Application.php(103): handleRequest
#2 /var/www/spdplus/releases/150/vendor/craftcms/cms/src/web/Application.php(276): handleRequest
#1 /var/www/spdplus/releases/150/vendor/yiisoft/yii2/base/Application.php(386): run
#0 index.php(25): null
```

#### Steps to reproduce
1. Create an element with Neo blocks
2. Add Quick Post Dashboard widget with this element

#### Other information
- Neo version: 2.6.2
- Craft version: 3.4.9

**Comment by pvldigital** [comment]
Hi @gglnx,

I’ve added a fix for this issue. Will be release in v2.6.3

**Comment by pvldigital** [comment]
Fix has been released for this issue
