### ISSUE TITLE
Database Exception when trying to save entry

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#362]
#### Description
I've got an entry with a number of Neo fields. One in particular seems to be causing the problem, `headerReadabilityTweaks` (not sure if the fieldname is relevant). It has 4 simple blocks, and I was able to add and remove them for a little bit, but now the entry is saved with two blocks, and doing anything to them—adding, deleting, or reordering them—results in a database exception, something about a missing `sortOrder` column in `field list`. O.o

#### Steps to reproduce
1. No
2. Freaking
3. Clue

#### Other information
- Neo version: 2.7.15
- Craft version: 3.4.19
- Is eager-loading used? No, but this is a backend issue anyway.

Here's the stack trace:

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sortOrder' in 'field list' in E:\Projects\HQ\vendor\yiisoft\yii2\db\Command.php:1293
Stack trace:
#0 E:\Projects\HQ\vendor\yiisoft\yii2\db\Command.php(1293): PDOStatement->execute()
#1 E:\Projects\HQ\vendor\yiisoft\yii2\db\Command.php(1093): yii\db\Command->internalExecute('UPDATE `craft_n...')
#2 E:\Projects\HQ\vendor\spicyweb\craft-neo\src\services\Fields.php(221): yii\db\Command->execute()
#3 E:\Projects\HQ\vendor\spicyweb\craft-neo\src\Field.php(689): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry))
#4 E:\Projects\HQ\vendor\craftcms\cms\src\base\Element.php(2559): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), false)
#5 E:\Projects\HQ\vendor\craftcms\cms\src\elements\Entry.php(1302): craft\base\Element->afterPropagate(false)
#6 E:\Projects\HQ\vendor\craftcms\cms\src\services\Elements.php(2146): craft\elements\Entry->afterPropagate(false)
#7 E:\Projects\HQ\vendor\craftcms\cms\src\services\Elements.php(531): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#8 E:\Projects\HQ\vendor\craftcms\cms\src\controllers\EntriesController.php(376): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#9 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#10 E:\Projects\HQ\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#11 E:\Projects\HQ\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 E:\Projects\HQ\vendor\craftcms\cms\src\web\Controller.php(178): yii\base\Controller->runAction('save-entry', Array)
#13 E:\Projects\HQ\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#14 E:\Projects\HQ\vendor\craftcms\cms\src\web\Application.php(291): yii\base\Module->runAction('entries/save-en...', Array)
#15 E:\Projects\HQ\vendor\craftcms\cms\src\web\Application.php(559): craft\web\Application->runAction('entries/save-en...', Array)
#16 E:\Projects\HQ\vendor\craftcms\cms\src\web\Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 E:\Projects\HQ\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 E:\Projects\HQ\web\index.php(21): yii\base\Application->run()
#19 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sortOrder' in 'field list'
The SQL being executed was: UPDATE `craft_neoblocks` SET `sortOrder`=1 WHERE `id`='185634' in E:\Projects\HQ\vendor\yiisoft\yii2\db\Schema.php:674
Stack trace:
#0 E:\Projects\HQ\vendor\yiisoft\yii2\db\Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'UPDATE `craft_n...')
#1 E:\Projects\HQ\vendor\yiisoft\yii2\db\Command.php(1093): yii\db\Command->internalExecute('UPDATE `craft_n...')
#2 E:\Projects\HQ\vendor\spicyweb\craft-neo\src\services\Fields.php(221): yii\db\Command->execute()
#3 E:\Projects\HQ\vendor\spicyweb\craft-neo\src\Field.php(689): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry))
#4 E:\Projects\HQ\vendor\craftcms\cms\src\base\Element.php(2559): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), false)
#5 E:\Projects\HQ\vendor\craftcms\cms\src\elements\Entry.php(1302): craft\base\Element->afterPropagate(false)
#6 E:\Projects\HQ\vendor\craftcms\cms\src\services\Elements.php(2146): craft\elements\Entry->afterPropagate(false)
#7 E:\Projects\HQ\vendor\craftcms\cms\src\services\Elements.php(531): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#8 E:\Projects\HQ\vendor\craftcms\cms\src\controllers\EntriesController.php(376): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#9 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#10 E:\Projects\HQ\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#11 E:\Projects\HQ\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 E:\Projects\HQ\vendor\craftcms\cms\src\web\Controller.php(178): yii\base\Controller->runAction('save-entry', Array)
#13 E:\Projects\HQ\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#14 E:\Projects\HQ\vendor\craftcms\cms\src\web\Application.php(291): yii\base\Module->runAction('entries/save-en...', Array)
#15 E:\Projects\HQ\vendor\craftcms\cms\src\web\Application.php(559): craft\web\Application->runAction('entries/save-en...', Array)
#16 E:\Projects\HQ\vendor\craftcms\cms\src\web\Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 E:\Projects\HQ\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 E:\Projects\HQ\web\index.php(21): yii\base\Application->run()
#19 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'sortOrder' in 'field list'
)

```

**Comment by pvldigital** [comment]
Hi @proimage,

Did you recently upgrade your craft from an older version to the latest? I've noticed there was a similar issue like yours and it was when the site was updated from craft 2 -> 3.

**Comment by proimage** [comment]
Nope, the site was originally built with 3.x.

**Comment by pvldigital** [comment]
Yeah the migration might not have run for some reason. Can you try running `./craft migrate/up --plugin=neo` and see if the migrations has been run?

**Comment by proimage** [comment]
:(

```bash
Yii Migration Tool (based on Yii v2.0.35)

No new migrations found. Your system is up-to-date.
```

**Comment by proimage** [comment]
I'm trying to understand a bit more of what exactly is going wrong here... Assuming that the `sortOrder` column mentioned is indeed missing somehow, what scope would that affect? Is that a column specific to the individual custom field where I'm seeing the problem, or would it affect all Neo fields?

Where in the database would I find the (lack of this) column? I do have backups going back quite a ways, but if it's a field-specific column, those backups may not have that field at all since it was created relatively recently (past few weeks).

**Comment by pvldigital** [comment]
`sortOrder` is used to check if there's any changes to the structure of the neo blocks. It'll update the structure if there's any changes else it would just save any content changes, this was done for delta updates and to improve the speed when saving an entry.

From your logs the column should be located in `craft_neoblocks`. It's strange how it the migration hasn't been applied, not sure what could've caused it.

Can you check within `craft_migrations` table for the update name `m200313_015120_structure_update`? If it's there you could try renaming it and rerunning the command in my previous comment to rerun the migration.
**Make sure to backup the DB before doing all this just in case.

**Comment by proimage** [comment]
That did the trick! I renamed it from `m200313_015120_structure_update` to `m200313_015120_structure_update2`, re-ran `./craft migrate/up --plugin=neo`, and got this result:

```
Yii Migration Tool (based on Yii v2.0.35)

Total 1 new migration to be applied:
        m200313_015120_structure_update

Apply the above migration? (yes|no) [no]:y
*** applying m200313_015120_structure_update
    > add column sortOrder integer AFTER `dateUpdated` to table {{%neoblocks}} ... done (time: 0.110s)
    > update in {{%neoblocks}} ... done (time: 0.016s)
    > update in {{%neoblocks}} ... done (time: 0.004s)
    > update in {{%neoblocks}} ... done (time: 0.004s)
    > update in {{%neoblocks}} ... done (time: 0.005s)
*** applied m200313_015120_structure_update (time: 0.250s)


1 migration was applied.

Migrated up successfully.
```

So now should I rename that migration back to the original name; is there a point in doing that?

**Comment by pvldigital** [comment]
Nope, should be fine to leave it as is.
