### ISSUE TITLE
Undefined index: maxSiblingBlocks

### ISSUE THREAD

**Issue by jerome2710** [spicywebau/craft-neo#382]
After upgrading the plugin to 2.8.0, the project-config/sync throws an error that `maxSiblingBlocks` is undefined. Re-saving all Neo-fields adds this setting to the config-files and fixes the issue.

```
2020-08-04 12:17:28 [-][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: maxSiblingBlocks in /.../vendor/spicyweb/craft-neo/src/services/BlockTypes.php:367
Stack trace:
#0 /.../vendor/spicyweb/craft-neo/src/services/BlockTypes.php(367): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/home/tde/domai...', 367, Array)
#1 /.../vendor/craftcms/cms/src/services/ProjectConfig.php(1090): benf\neo\services\BlockTypes->handleChangedBlockType(Object(craft\events\ConfigEvent))
#2 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#3 /.../vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#4 /.../vendor/craftcms/cms/src/services/ProjectConfig.php(668): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#5 /.../vendor/craftcms/cms/src/services/ProjectConfig.php(1080): craft\services\ProjectConfig->processConfigChanges('neoBlockTypes.1...')
#6 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#7 /.../vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#8 /.../vendor/craftcms/cms/src/services/ProjectConfig.php(662): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#9 /.../vendor/craftcms/cms/src/services/ProjectConfig.php(1180): craft\services\ProjectConfig->processConfigChanges('neoBlockTypes.1...', false, NULL, true)
#10 /.../vendor/craftcms/cms/src/services/ProjectConfig.php(528): craft\services\ProjectConfig->_applyChanges(Array)
#11 /.../vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(97): craft\services\ProjectConfig->applyYamlChanges()
#12 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#13 /.../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /.../vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#15 /.../vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('apply', Array)
#16 /.../vendor/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction('apply', Array)
#17 /.../vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(119): craft\console\Controller->runAction('apply')
#18 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#19 /.../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /.../vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#21 /.../vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('sync', Array)
#22 /.../vendor/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction('sync', Array)
#23 /.../vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('sync', Array)
#24 /.../vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#25 /.../vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('project-config/...', Array)
#26 /.../vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#27 /.../vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#28 /.../craft(24): yii\base\Application->run()
#29 {main}
```

**Comment by ttempleton** [comment]
Thanks for reporting this @jerome2710, it's fixed in 2.8.1.
