### ISSUE TITLE
Cannot apply Project Config changes

### ISSUE THREAD

**Issue by ccchapman** [spicywebau/craft-neo#383]
#### Description

When using Project Config and `allowAdminChanges` on Craft 3.5, Neo field changes cannot be applied automatically based on the configuration files.

This is a continuation of https://github.com/craftcms/cms/issues/6561.

#### Steps to reproduce

1. Make changes to a Neo field locally
1. Commit changes (notice that more Project Config files change than you'd expect)
1. Deploy to the primary environment and run `./craft project-config/apply`
1. Receive error below

```
2020-08-05 14:04:49 [-][-][-][error][yii\base\NotSupportedException] yii\base\NotSupportedException: Changes to the project config are not possible while in read-only mode. in /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php:446
Stack trace:
#0 /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(491): craft\services\ProjectConfig->set()
#1 /httpdocs/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(304): craft\services\ProjectConfig->remove()
#2 /httpdocs/vendor/spicyweb/craft-neo/src/services/Fields.php(103): benf\neo\services\BlockTypes->deleteGroupsByFieldId()
#3 /httpdocs/vendor/spicyweb/craft-neo/src/Field.php(616): benf\neo\services\Fields->save()
#4 /httpdocs/vendor/craftcms/cms/src/services/Fields.php(1661): benf\neo\Field->afterSave()
#5 /httpdocs/vendor/craftcms/cms/src/services/Fields.php(824): craft\services\Fields->applyFieldSave()
#6 /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(1089): craft\services\Fields->handleChangedField()
#7 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#8 /httpdocs/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#9 /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(667): yii\base\Component->trigger()
#10 /httpdocs/vendor/craftcms/cms/src/helpers/ProjectConfig.php(71): craft\services\ProjectConfig->processConfigChanges()
#11 /httpdocs/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(325): craft\helpers\ProjectConfig::ensureAllFieldsProcessed()
#12 /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(1089): benf\neo\services\BlockTypes->handleChangedBlockType()
#13 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#14 /httpdocs/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#15 /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(667): yii\base\Component->trigger()
#16 /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(1079): craft\services\ProjectConfig->processConfigChanges()
#17 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#18 /httpdocs/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#19 /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(661): yii\base\Component->trigger()
#20 /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(1179): craft\services\ProjectConfig->processConfigChanges()
#21 /httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(527): craft\services\ProjectConfig->_applyChanges()
#22 /httpdocs/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(97): craft\services\ProjectConfig->applyYamlChanges()
#23 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#24 /httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#25 /httpdocs/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#26 /httpdocs/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction()
#27 /httpdocs/vendor/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction()
#28 /httpdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction()
#29 /httpdocs/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#30 /httpdocs/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction()
#31 /httpdocs/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#32 /httpdocs/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#33 /httpdocs/craft(23): yii\base\Application->run()
#34 {main}
```

#### Other information
- Neo version: 2.8.2
- Craft version: 3.5.1

**Comment by ttempleton** [comment]
As also mentioned in #384, this will probably need to be fixed by changing how block type group resaving works (i.e. actually resaving a group if it's been changed, not just deleting the old one and creating a new one).

**Comment by ccchapman** [comment]
I also had an issue with block groups being duplicated and sometimes removed entirely. Same thing mentioned on the other issue. But it sounds like the resolution suggested above should solve that too. Thanks for the help!

**Comment by sjcallender** [comment]
For us, simply installing without creating fields doesn't translate into project config correctly either. A new environment doesn't end up getting Neo installed.

**Comment by ttempleton** [comment]
Neo 2.8.3 has just been released with the change to block type group resaving; @ccchapman, please update Neo and let me know if you're now able to run `./craft project-config/apply`.

@sjcallender, I think that is more likely to be a Craft issue, because Craft controls applying installed plugin data and basic field data; Neo itself only controls applying Neo fields' block types and block type groups.  If that does turn out to be another Neo bug, though, please feel free to open a new issue.

**Comment by ccchapman** [comment]
@ttempleton - I updated Neo to 2.8.3 and deployed some (Neo related) Project Config changes to an environment with setting changes disallowed. I can now apply the changes in that situation, where I would not be able to do so before.

The duplicate block categories needed to be manually removed from the primary environment DB, and then the corresponding Project Config needed to be committed.

Thanks for your quick help!

**Comment by ttempleton** [comment]
Thanks for confirming that, @ccchapman, glad to hear it's working now!
