### ISSUE TITLE
Cannot Rebuild Project Config

### ISSUE THREAD

**Issue by 23d1** [spicywebau/craft-neo#385]
#### Description
Here's the stack trace;

```
yii\base\ErrorException: Undefined offset: 967 in /var/www/craft/vendor/spicyweb/craft-neo/src/Plugin.php:187
Stack trace:
#0 /var/www/craft/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/craft/...', 187)
#1 /var/www/craft/vendor/spicyweb/craft-neo/src/Plugin.php(187): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/craft/...', 187, Array)
#2 [internal function]: benf\neo\Plugin->benf\neo\{closure}(Object(craft\events\RebuildConfigEvent))
#3 /var/www/craft/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\RebuildConfigEvent))
#4 /var/www/craft/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'rebuild', Object(craft\events\RebuildConfigEvent))
#5 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1149): yii\base\Component->trigger('rebuild', Object(craft\events\RebuildConfigEvent))
#6 /var/www/craft/vendor/craftcms/cms/src/controllers/UtilitiesController.php(177): craft\services\ProjectConfig->rebuild()
#7 [internal function]: craft\controllers\UtilitiesController->actionProjectConfigPerformAction()
#8 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/craft/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('project-config-...', Array)
#11 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('project-config-...', Array)
#12 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('utilities/proje...', Array)
#13 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction('utilities/proje...', Array)
#14 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(273): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /var/www/html/index.php(21): yii\base\Application->run()
#17 {main}
```

#### Steps to reproduce
1. Go to `Utilities` > `Project Config`
2. Hit `Rebuild` under Rebuild the Config

#### Other information
- Neo version: 2.8.2
- Craft version: 3.5.1

**Comment by ttempleton** [comment]
Thanks for reporting this, it seems to be happening when a block type's field layout consists only of blank tab(s) (in my case it was because of a tab that used to have a field that I'd deleted, so you should check if your affected field layout has a similar case), and it'll be fixed in the next release.  Note that, due to the fact Neo can no longer support blank tabs with Craft 3.5, project config rebuilds won't save any field layout data for a block type if the field layout only had blank tabs, and reapplying the project config after rebuilding it will cause the blank tabs to be lost.

**Comment by 23d1** [comment]
Thanks. That's good to know. Is it sufficient to add a header or something like that? Similar to the warning prior to upgrading a few releases back?

**Comment by ttempleton** [comment]
Yeah, that should be fine.

**Comment by ttempleton** [comment]
Neo 2.8.3 has just been released, which includes the fix for this error.
