### ISSUE TITLE
Error updating from 2.7.25 -> 2.8.3

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#389]
#### Description
After updating Neo to the latest version available for Craft 3.4.x (Neo v2.7.25), I successfully updated Craft to 3.5.x. Then I saw there were additional updates for Neo that required Craft 3.5+. But when I click "Update" for Neo, I get this:

```
A fatal error has occurred:

Status: Internal Server Error

Response: <pre>Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "yii\shell\Bootstrap".'

in E:\Projects\de\htdocs\vendor\yiisoft\yii2\di\Container.php:449

Stack trace:
#0 E:\Projects\de\htdocs\vendor\yiisoft\yii2\di\Container.php(374): yii\di\Container->getDependencies('yii\\shell\\Boots...')
#1 E:\Projects\de\htdocs\vendor\yiisoft\yii2\di\Container.php(159): yii\di\Container->build('yii\\shell\\Boots...', Array, Array)
#2 E:\Projects\de\htdocs\vendor\yiisoft\yii2\BaseYii.php(345): yii\di\Container->get('yii\\shell\\Boots...', Array)
#3 E:\Projects\de\htdocs\vendor\yiisoft\yii2\base\Application.php(294): yii\BaseYii::createObject('yii\\shell\\Boots...')
#4 E:\Projects\de\htdocs\vendor\craftcms\cms\src\web\Application.php(121): yii\base\Application->bootstrap()
#5 E:\Projects\de\htdocs\vendor\yiisoft\yii2\base\Application.php(273): craft\web\Application->bootstrap()
#6 E:\Projects\de\htdocs\vendor\craftcms\cms\src\web\Application.php(102): yii\base\Application->init()
#7 E:\Projects\de\htdocs\vendor\yiisoft\yii2\base\BaseObject.php(109): craft\web\Application->init()
#8 E:\Projects\de\htdocs\vendor\yiisoft\yii2\base\Application.php(206): yii\base\BaseObject->__construct(Array)
#9 E:\Projects\de\htdocs\vendor\craftcms\cms\src\web\Application.php(92): yii\base\Application->__construct(Array)
#10 [internal function]: craft\web\Application->__construct(Array)
#11 E:\Projects\de\htdocs\vendor\yiisoft\yii2\di\Container.php(400): ReflectionClass->newInstanceArgs(Array)
#12 E:\Projects\de\htdocs\vendor\yiisoft\yii2\di\Container.php(159): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#13 E:\Projects\de\htdocs\vendor\yiisoft\yii2\BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#14 E:\Projects\de\htdocs\vendor\craftcms\cms\bootstrap\bootstrap.php(245): yii\BaseYii::createObject(Array)
#15 E:\Projects\de\htdocs\vendor\craftcms\cms\bootstrap\web.php(51): require('E:\\Projects\\de...')
#16 E:\Projects\de\htdocs\web\index.php(20): require('E:\\Projects\\de...')
#17 {main}</pre>
```

I'm not sure if this is a Neo or Craft issue, but since it's happening while updating Neo, I'm posting it here.

**Comment by ttempleton** [comment]
Looks like this was a Craft issue: https://craftcms.stackexchange.com/questions/35974/craft-3-5-1-cli-update-error-failed-to-instantiate-component-or-class-yii-shel

I'll leave this issue open for now; please try the update again after following the instructions from the link, and let us know how it goes.

**Comment by proimage** [comment]
Ahh, that does indeed seem to have been the problem. Thanks!!
