### ISSUE TITLE
Running `project-config/apply` throws `UnknownMethodException` trying to access query.

### ISSUE THREAD

**Issue by leevigraham** [spicywebau/craft-neo#457]
#### Description

Running `project-config/apply` throws `UnknownMethodException`

This seems to be due `\benf\neo\elements\db\BlockQuery::_isRevisionRequest` calls `Craft::$app->request->getParam('token')` which is not available in the console

Probably introduced here: https://github.com/spicywebau/craft-neo/commit/a0b536e34dfb8c4251085e686b31a0a1e5e36e53

#### Steps to reproduce
1. Backup DB
2. Edit a neo field (saves project config)
3. Restore backup
4. Run `project-config/apply`

#### Other information
- Neo version: 2.9.8
- Craft version: 3.6.15

![image](https://user-images.githubusercontent.com/25124/119442617-88405580-bd6b-11eb-92dc-9e2730e56b49.png)

![Screen Shot 2021-05-25 at 15 04 24](https://user-images.githubusercontent.com/25124/119442255-d1dc7080-bd6a-11eb-89ba-d2312dd319e1.png)

<details>
<summary>Stack Trace</summary>
```
Stack trace:
#0 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(493): yii\base\Component->__call('getParam', Array)
#1 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(437): benf\neo\elements\db\BlockQuery->_isRevisionRequest()
#2 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1382): benf\neo\elements\db\BlockQuery->beforePrepare()
#3 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#4 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(benf\neo\elements\db\BlockQuery))
#5 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Query->createCommand(Object(craft\db\Connection))
#6 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
#7 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1547): craft\db\Query->all(NULL)
#8 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(268): craft\elements\db\ElementQuery->all(NULL)
#9 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(422): benf\neo\elements\db\BlockQuery->all()
#10 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/services/ProjectConfig.php(1185): benf\neo\services\BlockTypes->handleDeletedBlockType(Object(craft\events\ConfigEvent))
#11 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#12 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#13 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/services/ProjectConfig.php(742): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#14 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/services/ProjectConfig.php(1175): craft\services\ProjectConfig->_processConfigChangesInternal('neoBlockTypes.9...')
#15 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#16 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#17 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/services/ProjectConfig.php(742): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#18 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/services/ProjectConfig.php(1289): craft\services\ProjectConfig->_processConfigChangesInternal('neoBlockTypes.9...', false, NULL, true)
#19 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/services/ProjectConfig.php(569): craft\services\ProjectConfig->_applyChanges(Array)
#20 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(176): craft\services\ProjectConfig->applyYamlChanges()
#21 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#22 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#24 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('apply', Array)
#25 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/console/Controller.php(192): yii\console\Controller->runAction('apply', Array)
#26 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/base/Module.php(534): craft\console\Controller->runAction('apply', Array)
#27 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('project-config/...', Array)
#28 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('project-config/...', Array)
#29 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('project-config/...', Array)
#30 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#31 /Volumes/Sites/Work/Clients/aheadforbusiness.org.au/craft(8): yii\base\Application->run()
#32 {main}
```
</details>

**Comment by ttempleton** [comment]
I couldn't reproduce the error, but I just made a change for Neo 2.9.9 which will make sure the request isn't a console request before calling `getParam('token')`.

**Comment by leevigraham** [comment]
@ttempleton Yeah it was a bit of a weird one.
