### ISSUE TITLE
Children query throwing error when queried on sub site

### ISSUE THREAD

**Issue by angeloatzicht** [spicywebau/craft-neo#469]
We are running multiple "websites" under one (entries). This specific page does work perfectly when running under the "default" website, but when using a sub-website it will throw an error.

The specific part that throws an error is the part where we call the children of the overviewItems for the website "ikZoekBaas". As said, if we would query it for the "default" website then it works perfectly fine.

Everything seems oké, we activated this page for the "ikZoekBaas" website so it should work one would expect. But the result is the error shown in the screenshot.

#### Steps to reproduce
1. Create multiple websites (entries)
2. Create a page and activate it on multiple websites
3. Add the page to both the main website and a sub site
4. Query the page its overviewItems on the default website and a sub site 

#### Other information
- Neo version: 2.10.1
- Craft version: 3.6.17

![image](https://user-images.githubusercontent.com/76944829/122716876-1de7db80-d26b-11eb-803b-ede26d8c4aee.png)

**Comment by OscarBarrett** [comment]
Getting the same here since upgrading to 2.10.3.

It appears to have been introduced by this commit: https://github.com/spicywebau/craft-neo/commit/8031333098ab10e342e08b64821ef1b3ad7b4b54#diff-1d6ccd879666b18ea3d782414a63a52ff7c763d8c5fe4766ef5ce79ab6c9f781

[getElementById](https://docs.craftcms.com/api/v3/craft-services-elements.html#method-getelementbyid) can potentially return null. Adding an `isset($owner)` at the start of the return expression seems to fix it.

Full stack trace

```
ErrorException: Warning: First parameter must either be an object or the name of an existing class
#48 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(517): benf\neo\elements\db\BlockQuery::_ownerElementHasProp
#47 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(529): benf\neo\elements\db\BlockQuery::_isDraftRequest
#46 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(438): benf\neo\elements\db\BlockQuery::beforePrepare
#45 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1382): craft\elements\db\ElementQuery::prepare
#44 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(227): yii\db\QueryBuilder::build
#43 /app/vendor/yiisoft/yii2/db/Query.php(157): yii\db\Query::createCommand
#42 /app/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Query::all
#41 /app/vendor/craftcms/cms/src/db/Query.php(152): craft\db\Query::all
#40 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1547): craft\elements\db\ElementQuery::all
#39 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(270): benf\neo\elements\db\BlockQuery::all
#38 /app/vendor/spicyweb/craft-neo/src/gql/types/elements/Block.php(50): benf\neo\gql\types\elements\Block::resolve
#37 /app/vendor/craftcms/cms/src/gql/base/ObjectType.php(47): craft\gql\base\ObjectType::resolveWithDirectives
#36 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(624): GraphQL\Executor\ReferenceExecutor::resolveFieldValueOrError
#35 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(550): GraphQL\Executor\ReferenceExecutor::resolveField
#34 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1196): GraphQL\Executor\ReferenceExecutor::executeFields
#33 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1146): GraphQL\Executor\ReferenceExecutor::collectAndExecuteSubfields
#32 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1107): GraphQL\Executor\ReferenceExecutor::completeObjectValue
#31 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(975): GraphQL\Executor\ReferenceExecutor::completeAbstractValue
#30 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(790): GraphQL\Executor\ReferenceExecutor::completeValue
#29 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(655): GraphQL\Executor\ReferenceExecutor::completeValueCatchingError
#28 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(888): GraphQL\Executor\ReferenceExecutor::completeListValue
#27 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(762): GraphQL\Executor\ReferenceExecutor::completeValue
#26 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(655): GraphQL\Executor\ReferenceExecutor::completeValueCatchingError
#25 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\Executor\ReferenceExecutor::resolveField
#24 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1196): GraphQL\Executor\ReferenceExecutor::executeFields
#23 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1146): GraphQL\Executor\ReferenceExecutor::collectAndExecuteSubfields
#22 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1107): GraphQL\Executor\ReferenceExecutor::completeObjectValue
#21 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(975): GraphQL\Executor\ReferenceExecutor::completeAbstractValue
#20 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(790): GraphQL\Executor\ReferenceExecutor::completeValue
#19 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(655): GraphQL\Executor\ReferenceExecutor::completeValueCatchingError
#18 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\Executor\ReferenceExecutor::resolveField
#17 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1196): GraphQL\Executor\ReferenceExecutor::executeFields
#16 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(264): GraphQL\Executor\ReferenceExecutor::executeOperation
#15 /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(215): GraphQL\Executor\ReferenceExecutor::doExecute
#14 /app/vendor/webonyx/graphql-php/src/Executor/Executor.php(156): GraphQL\Executor\Executor::promiseToExecute
#13 /app/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\GraphQL::promiseToExecute
#12 /app/vendor/webonyx/graphql-php/src/GraphQL.php(94): GraphQL\GraphQL::executeQuery
#11 /app/vendor/craftcms/cms/src/services/Gql.php(545): craft\services\Gql::executeQuery
#10 /app/vendor/craftcms/cms/src/controllers/GraphqlController.php(172): craft\controllers\GraphqlController::actionApi
#9 [internal](0): call_user_func_array
#8 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#7 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Controller::runAction
#6 /app/vendor/craftcms/cms/src/web/Controller.php(190): craft\web\Controller::runAction
#5 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Module::runAction
#4 /app/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application::runAction
#3 /app/vendor/yiisoft/yii2/web/Application.php(104): yii\web\Application::handleRequest
#2 /app/vendor/craftcms/cms/src/web/Application.php(263): craft\web\Application::handleRequest
#1 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\base\Application::run
#0 /index.php(21): null
```

**Comment by ttempleton** [comment]
Thanks for reporting this @angeloatzicht and @OscarBarrett, the bug here was that we were failing to check the correct site when calling `getElementById()`, and the error should now be gone in Neo 2.10.4.

The lack of check for whether `getElementById()` returns `null` is intentional; that should only happen if we've given it invalid data (as was the case here with it effectively checking the incorrect site for the owner element), and an error should occur to alert us of that (Neo 2.10.4 does now include a more descriptive error than the old one, though).
