### ISSUE TITLE
Could not acquire a mutex lock for the queue (queue).

### ISSUE THREAD

**Issue by BAM-Dennis** [spicywebau/craft-neo#485]
#### Description
I just updated Craft from 3.4 to 3.7.5. I used the `./craft update all command` to update the system using the command line.
Everything went fine and alongside raft i also updated Neo, Supertable and some more irrelevant plugins.

After that some more updates appeared, which had another minimum System Requirement for Neo and Supertable. Again i used `./craft update all command` and the migrations went fine.

But now i have 1,8 million jobs in the queue with following error message:  `Could not acquire a mutex lock for the queue (queue).`

I retried all jobs using `./craft queue-manager/queue/retry-all` but if instantly fails with:

Jobs are mostly the following: `Applying new propagation method to Neo blocks`
We are on a 34 Site instance with a few 1000 Entries.

``` 
Exception 'yii\base\Exception' with message 'Could not acquire a mutex lock for the queue (queue).'

in /home/***/staging/vendor/craftcms/cms/src/queue/Queue.php:780

Stack trace:
#0 /home/***/staging/vendor/craftcms/cms/src/queue/Queue.php(618): craft\queue\Queue->_lock(Object(Closure))
#1 /home/***/staging/vendor/craftcms/cms/src/queue/Queue.php(130): craft\queue\Queue->reserve()
#2 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#3 /home/***/staging/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#4 /home/***/staging/vendor/craftcms/cms/src/queue/Queue.php(140): yii\queue\cli\Queue->runWorker(Object(Closure))
#5 /home/***/staging/vendor/craftcms/cms/src/queue/Command.php(77): craft\queue\Queue->run()
#6 [internal function]: craft\queue\Command->actionRun()
#7 /home/***/staging/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /home/***/staging/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#9 /home/***/staging/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('run', Array)
#10 /home/***/staging/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('run', Array)
#11 /home/***/staging/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('queue/run', Array)
#12 /home/***/staging/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('queue/run', Array)
#13 /home/***/staging/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('queue/run', Array)
#14 /home/***/staging/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /home/***/staging/craft(22): yii\base\Application->run()
#16 {main}
```

#### Steps to reproduce
1. Update from 3.4 to 3.75
2. Could not acquire a mutex lock for the queue (queue). appears afterwards
3.

#### Other information
- Neo version: 2.11.2
- Craft version: 3.7.5
- What is the affected Neo field's propagation method: Mostly "Only save blocks to the site they were created in" (none)

**Comment by BAM-Dennis** [comment]
Wrong repo. Closed
