### ISSUE TITLE
NEO 2.11.7 on Craft 3.7.10: MySQL crashes / Page save slow

### ISSUE THREAD

**Issue by maxstrebel** [spicywebau/craft-neo#494]
#### Description

Since the 3.7 Upgrade we experience weird behavior when changing NEO Blocks.

#### Steps to reproduce
1. Go to Entry with NEO Field
2. Change a value in a NEO field or create a new Block (worse)
3. Save
4. Save takes at least 10/20 Seconds
5. On production the SQL Server crashes

#### Other information
- Neo version: 2.11.7
- Craft version: 3.7.10
- (if multi-site) What is the affected Neo field's propagation method: Save Blocks to other sites in the same site group
- Is eager-loading used? No

#### Frontend

I don't know if this is related, but while investigating, I saw, that when saving in the frontend, the JS will throw the following Error

![image](https://user-images.githubusercontent.com/910594/130646693-690eaff4-4539-482f-b42b-d966665ffe63.png)

#### phperrors.log from production

````
[24-Aug-2021 17:04:37 Europe/Berlin] An Error occurred while handling another error:
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /html/.../vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /html/.../vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /html/.../vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /html/.../vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /html/.../vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /html/.../vendor/craftcms/cms/src/db/Query.php(258): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /html/.../vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /html/.../vendor/craftcms/cms/src/base/ApplicationTrait.php(391): yii\db\Query->count()
#7 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1444): craft\web\Application->getIsMultiSite(false, true)
#8 /html/.../vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /html/.../vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /html/.../vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /html/.../vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#12 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1607): craft\db\Query->one(NULL)
#13 /html/.../vendor/craftcms/cms/src/elements/User.php(452): craft\elements\db\ElementQuery->one()
#14 /html/.../vendor/yiisoft/yii2/web/User.php(700): craft\elements\User::findIdentity(1)
#15 /html/.../vendor/craftcms/cms/src/web/User.php(522): yii\web\User->renewAuthStatus()
#16 /html/.../vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#17 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(231): yii\web\User->getIdentity()
#18 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(141): craft\web\ErrorHandler->_showExceptionView()
#19 /html/.../vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#20 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(62): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#21 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#22 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
The SQL being executed was: SELECT COUNT(*)
FROM (SELECT 1
FROM `sites`
LIMIT 2) `x` in /html/.../vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /html/.../vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...')
#1 /html/.../vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /html/.../vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /html/.../vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /html/.../vendor/craftcms/cms/src/db/Query.php(258): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /html/.../vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /html/.../vendor/craftcms/cms/src/base/ApplicationTrait.php(391): yii\db\Query->count()
#7 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1444): craft\web\Application->getIsMultiSite(false, true)
#8 /html/.../vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /html/.../vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /html/.../vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /html/.../vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#12 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1607): craft\db\Query->one(NULL)
#13 /html/.../vendor/craftcms/cms/src/elements/User.php(452): craft\elements\db\ElementQuery->one()
#14 /html/.../vendor/yiisoft/yii2/web/User.php(700): craft\elements\User::findIdentity(1)
#15 /html/.../vendor/craftcms/cms/src/web/User.php(522): yii\web\User->renewAuthStatus()
#16 /html/.../vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#17 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(231): yii\web\User->getIdentity()
#18 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(141): craft\web\ErrorHandler->_showExceptionView()
#19 /html/.../vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#20 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(62): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#21 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#22 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 2006
    [2] => MySQL server has gone away
)

Previous exception:
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /html/.../vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /html/.../vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /html/.../vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /html/.../vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /html/.../vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /html/.../vendor/craftcms/cms/src/db/Query.php(258): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /html/.../vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /html/.../vendor/craftcms/cms/src/base/ApplicationTrait.php(391): yii\db\Query->count()
#7 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1444): craft\web\Application->getIsMultiSite(false, true)
#8 /html/.../vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /html/.../vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /html/.../vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /html/.../vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#12 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1607): craft\db\Query->one(NULL)
#13 /html/.../vendor/craftcms/cms/src/elements/User.php(452): craft\elements\db\ElementQuery->one()
#14 /html/.../vendor/yiisoft/yii2/web/User.php(700): craft\elements\User::findIdentity(1)
#15 /html/.../vendor/craftcms/cms/src/web/User.php(511): yii\web\User->renewAuthStatus()
#16 /html/.../vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#17 /html/.../vendor/craftcms/cms/src/web/Application.php(402): yii\web\User->getIdentity()
#18 /html/.../vendor/craftcms/cms/src/web/Application.php(95): craft\web\Application->debugBootstrap()
#19 /html/.../vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#20 /html/.../vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#21 [internal function]: yii\base\Application->__construct(Array)
#22 /html/.../vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#23 /html/.../vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#24 /html/.../vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#25 /html/.../vendor/craftcms/cms/bootstrap/bootstrap.php(242): yii\BaseYii::createObject(Array)
#26 /html/.../vendor/craftcms/cms/bootstrap/web.php(51): require('/html/utum-subd...')
#27 /html/.../web/index.php(21): require('/html/utum-subd...')
#28 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
The SQL being executed was: SELECT COUNT(*)
FROM (SELECT 1
FROM `sites`
LIMIT 2) `x` in /html/.../vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /html/.../vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...')
#1 /html/.../vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /html/.../vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /html/.../vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /html/.../vendor/craftcms/cms/src/db/Query.php(258): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /html/.../vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /html/.../vendor/craftcms/cms/src/base/ApplicationTrait.php(391): yii\db\Query->count()
#7 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1444): craft\web\Application->getIsMultiSite(false, true)
#8 /html/.../vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /html/.../vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /html/.../vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /html/.../vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#12 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1607): craft\db\Query->one(NULL)
#13 /html/.../vendor/craftcms/cms/src/elements/User.php(452): craft\elements\db\ElementQuery->one()
#14 /html/.../vendor/yiisoft/yii2/web/User.php(700): craft\elements\User::findIdentity(1)
#15 /html/.../vendor/craftcms/cms/src/web/User.php(511): yii\web\User->renewAuthStatus()
#16 /html/.../vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#17 /html/.../vendor/craftcms/cms/src/web/Application.php(402): yii\web\User->getIdentity()
#18 /html/.../vendor/craftcms/cms/src/web/Application.php(95): craft\web\Application->debugBootstrap()
#19 /html/.../vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#20 /html/.../vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#21 [internal function]: yii\base\Application->__construct(Array)
#22 /html/.../vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#23 /html/.../vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#24 /html/.../vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#25 /html/.../vendor/craftcms/cms/bootstrap/bootstrap.php(242): yii\BaseYii::createObject(Array)
#26 /html/.../vendor/craftcms/cms/bootstrap/web.php(51): require('/html/utum-subd...')
#27 /html/.../web/index.php(21): require('/html/utum-subd...')
#28 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 2006
    [2] => MySQL server has gone away
)

[24-Aug-2021 17:04:37 Europe/Berlin] An Error occurred while handling another error:
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /html/.../vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /html/.../vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /html/.../vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /html/.../vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /html/.../vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /html/.../vendor/craftcms/cms/src/db/Query.php(258): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /html/.../vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /html/.../vendor/craftcms/cms/src/base/ApplicationTrait.php(391): yii\db\Query->count()
#7 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1444): craft\web\Application->getIsMultiSite(false, true)
#8 /html/.../vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /html/.../vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /html/.../vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /html/.../vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#12 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1607): craft\db\Query->one(NULL)
#13 /html/.../vendor/craftcms/cms/src/elements/User.php(452): craft\elements\db\ElementQuery->one()
#14 /html/.../vendor/yiisoft/yii2/web/User.php(700): craft\elements\User::findIdentity(1)
#15 /html/.../vendor/craftcms/cms/src/web/User.php(522): yii\web\User->renewAuthStatus()
#16 /html/.../vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#17 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(231): yii\web\User->getIdentity()
#18 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(141): craft\web\ErrorHandler->_showExceptionView()
#19 /html/.../vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#20 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(62): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#21 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#22 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
The SQL being executed was: SELECT COUNT(*)
FROM (SELECT 1
FROM `sites`
LIMIT 2) `x` in /html/.../vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /html/.../vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...')
#1 /html/.../vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /html/.../vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /html/.../vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /html/.../vendor/craftcms/cms/src/db/Query.php(258): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /html/.../vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /html/.../vendor/craftcms/cms/src/base/ApplicationTrait.php(391): yii\db\Query->count()
#7 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1444): craft\web\Application->getIsMultiSite(false, true)
#8 /html/.../vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /html/.../vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /html/.../vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /html/.../vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#12 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1607): craft\db\Query->one(NULL)
#13 /html/.../vendor/craftcms/cms/src/elements/User.php(452): craft\elements\db\ElementQuery->one()
#14 /html/.../vendor/yiisoft/yii2/web/User.php(700): craft\elements\User::findIdentity(1)
#15 /html/.../vendor/craftcms/cms/src/web/User.php(522): yii\web\User->renewAuthStatus()
#16 /html/.../vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#17 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(231): yii\web\User->getIdentity()
#18 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(141): craft\web\ErrorHandler->_showExceptionView()
#19 /html/.../vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#20 /html/.../vendor/craftcms/cms/src/web/ErrorHandler.php(62): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#21 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#22 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 2006
    [2] => MySQL server has gone away
)

Previous exception:
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /html/.../vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /html/.../vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /html/.../vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /html/.../vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /html/.../vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /html/.../vendor/craftcms/cms/src/db/Query.php(258): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /html/.../vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /html/.../vendor/craftcms/cms/src/base/ApplicationTrait.php(391): yii\db\Query->count()
#7 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1444): craft\web\Application->getIsMultiSite(false, true)
#8 /html/.../vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /html/.../vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /html/.../vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /html/.../vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#12 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1607): craft\db\Query->one(NULL)
#13 /html/.../vendor/craftcms/cms/src/elements/User.php(452): craft\elements\db\ElementQuery->one()
#14 /html/.../vendor/yiisoft/yii2/web/User.php(700): craft\elements\User::findIdentity(1)
#15 /html/.../vendor/craftcms/cms/src/web/User.php(511): yii\web\User->renewAuthStatus()
#16 /html/.../vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#17 /html/.../vendor/craftcms/cms/src/web/Application.php(402): yii\web\User->getIdentity()
#18 /html/.../vendor/craftcms/cms/src/web/Application.php(95): craft\web\Application->debugBootstrap()
#19 /html/.../vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#20 /html/.../vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#21 [internal function]: yii\base\Application->__construct(Array)
#22 /html/.../vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#23 /html/.../vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#24 /html/.../vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#25 /html/.../vendor/craftcms/cms/bootstrap/bootstrap.php(242): yii\BaseYii::createObject(Array)
#26 /html/.../vendor/craftcms/cms/bootstrap/web.php(51): require('/html/utum-subd...')
#27 /html/.../web/index.php(21): require('/html/utum-subd...')
#28 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
The SQL being executed was: SELECT COUNT(*)
FROM (SELECT 1
FROM `sites`
LIMIT 2) `x` in /html/.../vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /html/.../vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...')
#1 /html/.../vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /html/.../vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /html/.../vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /html/.../vendor/craftcms/cms/src/db/Query.php(258): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /html/.../vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /html/.../vendor/craftcms/cms/src/base/ApplicationTrait.php(391): yii\db\Query->count()
#7 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1444): craft\web\Application->getIsMultiSite(false, true)
#8 /html/.../vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /html/.../vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /html/.../vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /html/.../vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#12 /html/.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1607): craft\db\Query->one(NULL)
#13 /html/.../vendor/craftcms/cms/src/elements/User.php(452): craft\elements\db\ElementQuery->one()
#14 /html/.../vendor/yiisoft/yii2/web/User.php(700): craft\elements\User::findIdentity(1)
#15 /html/.../vendor/craftcms/cms/src/web/User.php(511): yii\web\User->renewAuthStatus()
#16 /html/.../vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#17 /html/.../vendor/craftcms/cms/src/web/Application.php(402): yii\web\User->getIdentity()
#18 /html/.../vendor/craftcms/cms/src/web/Application.php(95): craft\web\Application->debugBootstrap()
#19 /html/.../vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#20 /html/.../vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#21 [internal function]: yii\base\Application->__construct(Array)
#22 /html/.../vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#23 /html/.../vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#24 /html/.../vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#25 /html/.../vendor/craftcms/cms/bootstrap/bootstrap.php(242): yii\BaseYii::createObject(Array)
#26 /html/.../vendor/craftcms/cms/bootstrap/web.php(51): require('/html/utum-subd...')
#27 /html/.../web/index.php(21): require('/html/utum-subd...')
#28 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 2006
    [2] => MySQL server has gone away
)

````

**Comment by michaelhue** [comment]
I'm experiencing a similar problem, saving entries with many Neo blocks will take up to one minute since upgrading to Craft 3.7. The queue also fills up with hundreds, sometimes thousands of search index update tasks.

The trace details below show an entry save action that took 48 seconds. I can provide a link to more information if needed.

![Bildschirmfoto 2021-08-24 um 19 02 24](https://user-images.githubusercontent.com/31861/130659217-c21d2dc7-e2d2-40ff-991b-fbb9f7e37ec2.png)

**Comment by turnstylerj** [comment]
I believe we may be experiencing this same issue with Craft 3.7.10 and Neo 2.11.8. Entries with several Neo blocks are taking 20-30 seconds to save on a multi-site install with 4 languages. This is a pretty early in-development site, so there isn't a ton of content, less than 10 blocks on each entry experiencing the issue. Please let me know if there's anything else I can provide that may be helpful.

**Comment by maxstrebel** [comment]
Yeah, the problem is back. I had to Rollback to 3.6. I can share what I know so far:

- It's a problem with table locks. MySQL gets stuck with locked tables
- I don't know if this NEO related, honestly, because the DB sometimes also gets stuck, when I want to do a migration (see screenshot)
- I could imagine it has something to do with the new changes how content is merged?

![image](https://user-images.githubusercontent.com/910594/131995003-bcd4485a-229c-4e03-a682-f6cbf5bf6b8e.png)

**Comment by michaelhue** [comment]
I can also confirm that will still have the performance problem with long loading times. I also suspect that is has to do with how Craft 3.7 manages drafts/revisions.

Disabling the `autosaveDrafts` config setting has helped somewhat, but that also disables Live Preview. 

I can provide access to New Relic data if that helps at all.

**Comment by sjcallender** [comment]
We are definitely experiencing this on a large multi-site build with Craft 3.7.11 and Neo 2.11.9. Our db server is never hitting more than 2% utilization. For us, it happens when both saving changes on the Current version and when attempting to Apply the Draft.

**Comment by ttempleton** [comment]
Does this happen if you downgrade to Neo 2.11.2? There were changes in 2.11.3 to fix a block structure-related merging bug which shouldn't have caused this kind of issue, but want to confirm that if possible.

**Comment by sjcallender** [comment]
@ttempleton - Unfortunately, downgrading to 2.11.2 didn't help.

**Comment by ttempleton** [comment]
Thanks @sjcallender. I agree with @michaelhue that this is likely related to those changes in Craft 3.7. That said, besides block structure management (which I don't believe is causing this, if there's no difference in performance between Neo 2.11.2 and later versions), Neo shouldn't be doing anything particularly special when content merging happens, compared with Matrix. It would be greatly appreciated if anyone having performance issues when saving Neo content can confirm whether or not you also have performance issues if you try to save a similar amount of Matrix content.

**Comment by sjcallender** [comment]
No problem. I tried an entry with only Matrix blocks and you're right. It takes just about as long. It didn't error out, because it completed in about 95 seconds, just under the 100 second Cloudflare timeout value.

**Comment by sjcallender** [comment]
@michaelhue - Are you seeing the same issue when trying to "apply" a draft too (vs just saving the provisional draft on the current version of the entry)?

**Comment by ttempleton** [comment]
Thanks for confirming that, @sjcallender. Going to close this issue and redirect discussion to https://github.com/craftcms/cms/issues/9789 for now, but will reopen this issue if any future performance improvements in Craft for Matrix fields do not also improve performance with Neo.
