### ISSUE TITLE
Error when cloning or pasting a Neo block that uses the child blocks UI element

### ISSUE THREAD

**Issue by danwill** [spicywebau/craft-neo#512]
#### Description

When cloning or copy/pasting a Neo block with child blocks that makes use of the child blocks UI element, a server error occurs, and the block is not duplicated. 

The issue seems to be that the child block UI element item is contained in the `$_POST` collection, but has a key of undefined:

```
[-][1][tu30h7eefcde33g00asfml5mi6][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\behaviors\CustomFieldBehavior::undefined in ***/vendor/yiisoft/yii2/base/BaseObject.php:163
Stack trace:
#0 ***/storage/runtime/compiled_classes/CustomFieldBehavior_lymluxbwieeq.php(454): yii\base\BaseObject->__set('undefined', '3640')
#1 ***/vendor/craftcms/cms/src/base/Element.php(3320): craft\behaviors\CustomFieldBehavior->__set('undefined', '3640')
#2 ***/vendor/craftcms/cms/src/base/Element.php(3299): craft\base\Element->setFieldValue('undefined', '3640')
#3 ***/vendor/spicyweb/craft-neo/src/controllers/Input.php(59): craft\base\Element->setFieldValues(Array)
#4 [internal function]: benf\neo\controllers\Input->actionRenderBlocks()

---

$_POST = [
    'namespace' => 'fields[pageContent][blocks]'
    'blocks' => [
        0 => [
            'collapsed' => '0'
            'content' => [
                'eyebrow' => ''
                'headline' => 'Lorem ipsum dolor'
                'description' => '<p>Rem reprehenderit at ab saepe! Incidunt a dignissimos sed voluptatem doloribus modi ducimus repudiandae. Nam optio ducimus totam minima a dolores assumenda!</p>'
                'undefined' => '3640'
                'bgColor' => ''
                'contentStyle' => ''
                'buttonStyle' => ''
            ]
            'enabled' => '1'
            'level' => '0'
            'ownerId' => ''
            'type' => '19'
        ]
        1 => [
            'collapsed' => '0'
            'content' => [
                'headline' => 'Lorem ipsum dolor'
                'description' => '<p>Rem reprehenderit at ab saepe! Incidunt a dignissimos sed voluptatem doloribus modi ducimus repudiandae. Nam optio ducimus totam minima a dolores assumenda!</p>'
            ]
            'enabled' => '1'
            'level' => '1'
            'ownerId' => ''
            'type' => '20'
        ]
    ]
]
```
With the following field layout:

<img width="509" alt="neo-block-config" src="https://user-images.githubusercontent.com/1927471/141174003-553c1b47-aace-4c0a-8f2f-9dc6aec4c5da.png">

The 2.10.7 release appears to have targeted a similar issue.

#### Steps to reproduce
1. Create a Neo block that allows for child blocks, and that uses the Child Block UI element to control layout on an edit page.
2. Add the block to a page, and add at least 1 child block
3. Either copy/paste the parent block, or clone it
4. "A server error has occurred..." message will appear 

#### Other information
- Neo version: 2.11.16
- Craft version: Craft Pro 3.7.20
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Thanks for reporting this! Fixed now in Neo 2.11.17.
