### ISSUE TITLE
Error when trying to update to 2.13.6

### ISSUE THREAD

**Issue by lukasNo1** [spicywebau/craft-neo#566]
#### Description
I recently updated a craft 2 installation to craft 3.7.30.1 and neo 2.12.4 which went without great problems.

For neo to work, I had to apply this fix manually though: https://github.com/spicywebau/craft-neo/issues/172 - manually create maxChildBlocks field 

Now i tried to update to neo 2.13.6 and got this error:

Any ideas?
The site is not multi site.

```
*** applying m220228_081104_add_group_id_to_block_types
    > add column groupId integer AFTER `fieldLayoutId` to table {{%neoblocktypes}} ... done (time: 0.059s)
    > create index craft_idx_zhcqvdjgrrzhmlqtxaisbgusidlxjhpvqttw on {{%neoblocktypes}} (groupId) ... done (time: 0.016s)
    > add foreign key craft_fk_ocfaukpxkpatvavgkhgesjccougyuyolcscf: {{%neoblocktypes}} (groupId) references {{%neoblocktypegroups}} (id) ... done (time: 0.049s)
Exception: Undefined array key "field" (/var/www/backend/vendor/spicyweb/craft-neo/src/services/BlockTypes.php:359)
#0 /var/www/backend/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(359): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/backen...', 359)
#1 /var/www/backend/vendor/craftcms/cms/src/services/ProjectConfig.php(1199): benf\neo\services\BlockTypes->handleChangedBlockType(Object(craft\events\ConfigEvent))
#2 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#3 /var/www/backend/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#4 /var/www/backend/vendor/craftcms/cms/src/services/ProjectConfig.php(768): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#5 /var/www/backend/vendor/craftcms/cms/src/services/ProjectConfig.php(1189): craft\services\ProjectConfig->_processConfigChangesInternal('neoBlockTypes.8...')
#6 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#7 /var/www/backend/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#8 /var/www/backend/vendor/craftcms/cms/src/services/ProjectConfig.php(768): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#9 /var/www/backend/vendor/craftcms/cms/src/services/ProjectConfig.php(544): craft\services\ProjectConfig->_processConfigChangesInternal('neoBlockTypes.8...', true, NULL)
#10 /var/www/backend/vendor/spicyweb/craft-neo/src/migrations/m220228_081104_add_group_id_to_block_types.php(61): craft\services\ProjectConfig->set('neoBlockTypes.8...', '6472c7df-0e2e-4...')
#11 /var/www/backend/vendor/craftcms/cms/src/db/Migration.php(53): benf\neo\migrations\m220228_081104_add_group_id_to_block_types->safeUp()
#12 /var/www/backend/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#13 /var/www/backend/vendor/craftcms/cms/src/console/controllers/MigrateController.php(386): yii\console\controllers\BaseMigrateController->migrateUp('m220228_081104_...')
#14 [internal function]: craft\console\controllers\MigrateController->actionAll()
#15 /var/www/backend/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/backend/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/backend/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('all', Array)
#18 /var/www/backend/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#19 /var/www/backend/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#20 /var/www/backend/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#21 /var/www/backend/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#22 /var/www/backend/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#23 /var/www/backend/craft(20): yii\base\Application->run()
#24 {main}


```

**Comment by lukasNo1** [comment]
The error is fixed now, i needed to rebuild the project config.
