### ISSUE TITLE
Garnish Console Error after Updating Neo to Version 2.10.8

### ISSUE THREAD

**Issue by fabianhaef** [spicywebau/craft-neo#591]
#### Description
After updating Craft CMS and some plugins I get the following error when trying to edit Neo Blocks in the control panel:

`Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at s.constructor.trigger (garnish.js:834:17)
    at s.constructor.init (MatrixInput.js:140:22)
    at s.constructor.constructor (garnish.js:764:19)
    at s.constructor (garnish.js:40:17)
    at new s.constructor (garnish.js:40:17)
    at <anonymous>:121:19
    at m (jquery.js:133:12)
    at Oe (jquery.js:6114:8)
    at b.fn.init.append (jquery.js:6250:10)
    at s.constructor.initUi (main.js?v=1654092251:13:30224) 

Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at s.constructor.trigger (garnish.js:834:17)
    at s.constructor.initRedactor (RedactorInput.js:217:22)
    at s.constructor.init (RedactorInput.js:145:22)
    at s.constructor.constructor (garnish.js:764:19)
    at s.constructor (garnish.js:40:17)
    at new s.constructor (garnish.js:40:17)
    at <anonymous>:246:1
    at m (jquery.js:133:12)
    at Oe (jquery.js:6114:8)
    at b.fn.init.append (jquery.js:6250:10)

jquery.js:4059 Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at s.constructor.trigger (garnish.js:834:17)
    at s.constructor.initUi (main.js?v=1654092251:13:31581)
    at s.constructor.addBlock (main.js?v=1654092251:13:1517)
    at s.constructor.init (main.js?v=1654092251:12:31905)
    at s.constructor.constructor (garnish.js:764:19)
    at s.constructor (garnish.js:40:17)
    at new s.constructor (garnish.js:40:17)
    at Object.createInput (main.js?v=1654092251:1:660)
    at HTMLDocument.<anonymous> (7745-hotel-kaiserstuhl:1570:5)
    at l (jquery.js:3766:29)`

I have already tried to delete the control panel resources, deactivate all plugins and activate them again. The following plugins are installed:
Architect - v2.4.3
Delete Entry Versions - v2.0.0
Expanded Singles - v1.2.0
Field Manager - v2.2.0
Isolate - v1.4.4
Linkit - v1.1.12.1
Locate - v2.1.1
Neo - v2.10.8
Redactor - v.2.9.1
Sprout Active - v2.2.0
XML Sitemap - v.1.3.2

#### Other information
<img width="479" alt="Bildschirmfoto 2022-06-01 um 16 16 59" src="https://user-images.githubusercontent.com/55360588/171426304-fd2a8801-71f6-4ac2-a09a-05d0de73686e.png">

- Neo version: 2.10.8
- Craft version: 3.6.18

- Is eager-loading used? No

**Comment by ttempleton** [comment]
Looks like #540 is happening to you again! That should be fixed by upgrading Redactor, then. Let me know if it's still happening after upgrading it, though!

**Comment by fabianhaef** [comment]
Thanks, this fixed it.
