### ISSUE TITLE
m220409_142203_neoblocks_owners_table failed during Craft 3->4 migration

### ISSUE THREAD

**Issue by wei2go** [spicywebau/craft-neo#635]
#### Steps to reproduce
1. Follow the migration steps in: https://craftcms.com/docs/4.x/upgrade.html
2. At the last step, run `php craft migrate/all`
3. The console fires the error: failed to apply m220409_142203_neoblocks_owners_table

#### Other information
- Neo version: from 2.13.15 to 3.2.5
- Craft version: from 3.7.50 to 4.2.0
- (if multi-site) What is the affected Neo field's propagation method: not multi-site
- Is eager-loading used? - don't remember, but probably not.

#### Details
Errors:
```
applying m220409_142203_neoblocks_owners_table
    > dropping {{%neoblocks_owners}} if it exists ... done (time: 0.000s)
    > create table {{%neoblocks_owners}} ... done (time: 0.009s)
    > add foreign key fk_tygonwlvrpjckjjmttkidpbxxasslttaawaa: {{%neoblocks_owners}} (blockId) references {{%neoblocks}} (id) ... done (time: 0.027s)
    > add foreign key fk_xtevhkvsazvpkkafyzxpohyclzhsyjqwfxog: {{%neoblocks_owners}} (ownerId) references {{%elements}} (id) ... done (time: 0.026s)
    > execute SQL: INSERT INTO {{%neoblocks_owners}} ([[blockId]], [[ownerId]], [[sortOrder]])
SELECT [[id]], [[ownerId]], [[sortOrder]]
FROM {{%neoblocks}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sortOrder' cannot be null
The SQL being executed was: INSERT INTO `neoblocks_owners` (`blockId`, `ownerId`, `sortOrder`)
SELECT `id`, `ownerId`, `sortOrder`
FROM `neoblocks` (D:\projects\test\vendor\yiisoft\yii2\db\Schema.php:676)
#0 D:\projects\test\vendor\yiisoft\yii2\db\Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `ne...')
#1 D:\projects\test\vendor\yiisoft\yii2\db\Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `ne...')
#2 D:\projects\test\vendor\yiisoft\yii2\db\Migration.php(219): yii\db\Command->execute()
#3 D:\projects\test\vendor\spicyweb\craft-neo\src\migrations\m220409_142203_neoblocks_owners_table.php(36): yii\db\Migration->execute('INSERT INTO {{%...')
#4 D:\projects\test\vendor\craftcms\cms\src\db\Migration.php(49): benf\neo\migrations\m220409_142203_neoblocks_owners_table->safeUp()
#5 D:\projects\test\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(758): craft\db\Migration->up()
#6 D:\projects\test\vendor\craftcms\cms\src\console\controllers\MigrateController.php(360): yii\console\controllers\BaseMigrateController->migrateUp('m220409_142203_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 D:\projects\test\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#9 D:\projects\test\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 D:\projects\test\vendor\yiisoft\yii2\console\Controller.php(182): yii\base\Controller->runAction('all', Array)
#11 D:\projects\test\vendor\yiisoft\yii2\base\Module.php(552): yii\console\Controller->runAction('all', Array)
#12 D:\projects\test\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#13 D:\projects\test\vendor\craftcms\cms\src\console\Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#14 D:\projects\test\vendor\yiisoft\yii2\console\Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#15 D:\projects\test\vendor\craftcms\cms\src\console\Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 D:\projects\test\vendor\yiisoft\yii2\base\Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#17 D:\projects\test\craft(22): yii\base\Application->run()
#18 {main}
*** failed to apply m220409_142203_neoblocks_owners_table (time: 0.070s)
```

- I checked `m220409_142203_neoblocks_owners_table`, it shows that `sortOrder` in `neoblocks_owners` table is `notNull()`.
- However, when I checked the table structure of `neoblocks` (prior to migration), `neoblocks.sortOrder` allows Null and defaults to Null, and I do have some `neoblocks` rows has `sortOrder` as NULL. I think that's why this migration script fails, as it tries to `INSERT INTO 'neoblocks_owners' ('blockId', 'ownerId', 'sortOrder') SELECT 'id', 'ownerId', 'sortOrder' FROM 'neoblocks'`

Any advice for the fix?

**Comment by wei2go** [comment]
Never mind. I resolved the issue by running `php craft gc` to clean up database before the migration.
