### ISSUE TITLE
3.3.0 fails to install

### ISSUE THREAD

**Issue by boboldehampsink** [spicywebau/craft-neo#640]
#### Description

```
applying existing project config ... Exception: Undefined array key "minBlocks" (/app/user/vendor/spicyweb/craft-neo/src/services/BlockTypes.php:427)
--
  | #0 /app/user/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(427): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/app/user/vendo...', 427)
  | #1 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1125): benf\neo\services\BlockTypes->handleChangedBlockType(Object(craft\events\ConfigEvent))
  | #2 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
  | #3 /app/user/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
  | #4 /app/user/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
  | #5 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1115): craft\models\ProjectConfigData->commitChanges(NULL, Array, 'neoBlockTypes.7...')
  | #6 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
  | #7 /app/user/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
  | #8 /app/user/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
  | #9 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1231): craft\models\ProjectConfigData->commitChanges(NULL, Array, 'neoBlockTypes.7...', true, NULL, true)
  | #10 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1253): craft\services\ProjectConfig->craft\services\{closure}('neoBlockTypes.7...', true)
  | #11 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(577): craft\services\ProjectConfig->_applyChanges(Array, Object(craft\models\ProjectConfigData), Object(craft\models\ReadOnlyProjectConfigData))
  | #12 /app/user/vendor/craftcms/cms/src/migrations/Install.php(1133): craft\services\ProjectConfig->applyExternalChanges()
  | #13 /app/user/vendor/craftcms/cms/src/migrations/Install.php(78): craft\migrations\Install->insertDefaultData()
  | #14 /app/user/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\Install->safeUp()
  | #15 /app/user/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
  | #16 /app/user/vendor/craftcms/cms/src/console/controllers/InstallController.php(211): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
  | #17 [internal function]: craft\console\controllers\InstallController->actionCraft()
  | #18 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
  | #19 /app/user/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
  | #20 /app/user/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('', Array)
  | #21 /app/user/vendor/craftcms/cms/src/console/Controller.php(224): yii\console\Controller->runAction('', Array)
  | #22 /app/user/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
  | #23 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
  | #24 /app/user/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('install', Array)
  | #25 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
  | #26 /app/user/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
  | #27 /app/user/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
  | #28 /app/user/craft(24): yii\base\Application->run()
  | #29 {main}
```

#### Steps to reproduce
I updated Neo to 3.3.0 and did a fresh install with the new project config

#### Other information
- Neo version: 3.3
- Craft version: 4
- (if multi-site) What is the affected Neo field's propagation method: no
- Is eager-loading used? yes

**Comment by ttempleton** [comment]
Thanks for reporting that - should be fixed now in 3.3.1.

**Comment by boboldehampsink** [comment]
Now seeing this in 3.3.1:

```


PHP Warning 'yii\base\ErrorException' with message 'Undefined array key 8'
--
  |  
  | in /app/user/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php:158
  |  
  | Stack trace:
  | #0 /app/user/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php(158): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/app/user/vendo...', 158)
  | #1 /app/user/vendor/spicyweb/craft-neo/src/Field.php(705): benf\neo\validators\FieldValidator->validateAttribute(Object(craft\elements\Entry), 'productBlocks')
  | #2 /app/user/vendor/craftcms/cms/src/base/Element.php(2359): benf\neo\Field->validateBlocks(Object(craft\elements\Entry), NULL)
  | #3 /app/user/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\base\Element->validateCustomFieldAttribute('field:productBl...', Array, Object(yii\validators\InlineValidator), Object(benf\neo\elements\db\BlockQuery))
  | #4 /app/user/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'field:productBl...')
  | #5 /app/user/vendor/craftcms/cms/src/base/Element.php(2260): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry))
  | #6 /app/user/vendor/yiisoft/yii2/base/Model.php(369): craft\base\Element->afterValidate()
  | #7 /app/user/vendor/craftcms/cms/src/services/Elements.php(2572): yii\base\Model->validate()
  | #8 /app/user/vendor/craftcms/cms/src/services/Elements.php(795): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, false)
  | #9 /app/user/vendor/craftcms/cms/src/test/fixtures/elements/BaseElementFixture.php(154): craft\services\Elements->saveElement(Object(craft\elements\Entry), true, true, false)
  | #10 /app/user/vendor/craftcms/cms/src/test/fixtures/elements/BaseElementFixture.php(84): craft\test\fixtures\elements\BaseElementFixture->saveElement(Object(craft\elements\Entry))
  | #11 /app/user/vendor/yiisoft/yii2/test/FixtureTrait.php(96): craft\test\fixtures\elements\BaseElementFixture->load()
  | #12 /app/user/vendor/yiisoft/yii2/console/controllers/FixtureController.php(159): yii\console\controllers\FixtureController->loadFixtures(Array)
  | #13 [internal function]: yii\console\controllers\FixtureController->actionLoad(Array)
  | #14 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
  | #15 /app/user/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
  | #16 /app/user/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('load', Array)
  | #17 /app/user/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('load', Array)
  | #18 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('fixture/load', Array)
  | #19 /app/user/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('fixture/load', Array)
  | #20 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('fixture/load', Array)
  | #21 /app/user/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
  | #22 /app/user/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
  | #23 /app/user/craft(24): yii\base\Application->run()
  | #24 {main}


```

**Comment by ttempleton** [comment]
See #639
