### ISSUE TITLE
Craft 3 -> 4 Migration issue (neoblocks_owners)

### ISSUE THREAD

**Issue by mediabeastnz** [spicywebau/craft-neo#654]
#### Description
We've been running into an issue while upgrading all our Craft 3 sites that use this plugin.
The issue seems to be related to the migration `m220409_142203_neoblocks_owners_table.php`

The first issue is this (Which we can resolve manually but still seems dangerous to do)
```sql
SELECT [[id]], [[ownerId]], [[sortOrder]] 
FROM {{%neoblocks}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sortOrder' cannot be null
The SQL being executed was: INSERT INTO `neoblocks_owners` (`blockId`, `ownerId`, `sortOrder`) 
SELECT `id`, `ownerId`, `sortOrder` 
FROM `neoblocks` 
```

The second issue is (which can't be manually resolved):
```sql
SELECT [[id]], [[ownerId]], [[sortOrder]] 
FROM {{%neoblocks}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db`.`neoblocks_owners`, CONSTRAINT `fk_aupenilsoeilxkwkebslzzaajokwhiufxtkh` FOREIGN KEY (`ownerId`) REFERENCES `elements` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `neoblocks_owners` (`blockId`, `ownerId`, `sortOrder`) 
SELECT `id`, `ownerId`, `sortOrder` 
FROM `neoblocks`
```

As a way to debug this ourselves, we commented out the following piece of code (as a test) to see if the rest of the migrations succeeded, which they did.

```sql
$this->execute(<<<SQL
INSERT INTO $ownersTable ([[blockId]], [[ownerId]], [[sortOrder]]) 
SELECT [[id]], [[ownerId]], [[sortOrder]] 
FROM $blocksTable
SQL
);
```

**How do we go about fixing this as we're wanting to upgrade all our sites (there quite a few)?**

#### Steps to reproduce
1. Upgrade Craft to 4.*
2. Follow Craft upgrade guide
3. Run migrations

#### Other information
- Neo version: 2.13.15 to 3.3.8
- Craft version: 3.7.54 to 4.*
- (if multi-site) What is the affected Neo field's propagation method: na
- Is eager-loading used? na

**Comment by ttempleton** [comment]
This issue didn't come up when I was recently working on #649, but I assume this is the Neo equivalent to the Matrix issue https://github.com/craftcms/cms/issues/11843, so I've just applied the same fix (https://github.com/craftcms/cms/commit/a01c8c636a2db6c47537cfa0d4a19f8b90a52242) to Neo. For now, you can get that fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.3.8` and running `composer update`.

**Comment by mediabeastnz** [comment]
Thanks @ttempleton we'll try that and let you know

**Comment by merwinpoulose** [comment]
Hi @ttempleton @mediabeastnz   Thanks, we just tried changing spicyweb/craft-neo requirement to `3.x-dev as 3.3.8` and ran composer update, then ran `php craft migrate/all` .

The issue with` 'sortOrder' cannot be null` got resolved but still we are having issue with migration.  It's still complaining about foreign key constraint fails. Here is the error after running migrations


```
*** applying m220409_142203_neoblocks_owners_table
    > dropping {{%neoblocks_owners}} if it exists ... done (time: 0.000s)
    > create table {{%neoblocks_owners}} ... done (time: 0.004s)
    > add foreign key fk_flcxbfjhcpzrejqjowhtecgzagtrywxlnyfv: {{%neoblocks_owners}} (blockId) references {{%neoblocks}} (id) ... done (time: 0.013s)
    > add foreign key fk_jhgavjebxolvbvectegrbgrnjxnhrphdmwtl: {{%neoblocks_owners}} (ownerId) references {{%elements}} (id) ... done (time: 0.008s)
    > execute SQL: INSERT INTO {{%neoblocks_owners}} ([[blockId]], [[ownerId]], [[sortOrder]]) 
SELECT [[id]], [[ownerId]], COALESCE([[sortOrder]], 1) 
FROM {{%neoblocks}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db`.`neoblocks_owners`, CONSTRAINT `fk_jhgavjebxolvbvectegrbgrnjxnhrphdmwtl` FOREIGN KEY (`ownerId`) REFERENCES `elements` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `neoblocks_owners` (`blockId`, `ownerId`, `sortOrder`) 
SELECT `id`, `ownerId`, COALESCE(`sortOrder`, 1) 
FROM `neoblocks` (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `ne...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `ne...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
#3 /var/www/html/vendor/spicyweb/craft-neo/src/migrations/m220409_142203_neoblocks_owners_table.php(36): yii\db\Migration->execute('INSERT INTO {{%...')
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): benf\neo\migrations\m220409_142203_neoblocks_owners_table->safeUp()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(360): yii\console\controllers\BaseMigrateController->migrateUp('m220409_142203_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('all', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#13 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#17 /var/www/html/craft(14): yii\base\Application->run()
#18 {main}
*** failed to apply m220409_142203_neoblocks_owners_table (time: 0.033s)


42 from 55 migrations were applied.

Migration failed. The rest of the migrations are canceled.
Failed to run php craft migrate/all: exit status 1
```

**Comment by ttempleton** [comment]
Could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au and we'll have a look.

**Comment by mediabeastnz** [comment]
> Could you please send your composer.json/lock and database backup to [plugins@spicyweb.com.au](mailto:plugins@spicyweb.com.au) and we'll have a look.

Hey @ttempleton I work with @merwinpoulose, unfortunately we can't send a database backup to you as this has sensitive order information store in there.

Are there specific tables we can send?

**Comment by ttempleton** [comment]
No worries - shouldn't be necessary to send anything in now, since it looks to be the Neo equivalent of https://github.com/craftcms/cms/issues/11506. Following the advice from https://github.com/craftcms/cms/issues/11506#issuecomment-1175726423 (except substituting `supertableblocks`/`matrixblocks` with `neoblocks`) should resolve it.
