### ISSUE TITLE
GraphQL query failure after Craft 3.5 to 4.0 upgrade

### ISSUE THREAD

**Issue by davola** [spicywebau/craft-neo#678]
#### Description
When trying to access any graphql query , the neo plugin breaks it with the following error:

> Cannot assign craft\\fields\\PlainText to property benf\\neo\\models\\BlockType::$_field of type ?benf\\neo\\Field

The stack trace is as follows:
```
[web.ERROR] [TypeError] TypeError: Cannot assign craft\fields\PlainText to property benf\neo\models\BlockType::$_field of type ?benf\neo\Field in /app/vendor/spicyweb/craft-neo/src/models/BlockType.php:235
Stack trace:
#0 /app/vendor/spicyweb/craft-neo/src/elements/Block.php(146): benf\neo\models\BlockType->getField()
#1 /app/vendor/spicyweb/craft-neo/src/gql/types/generators/BlockType.php(51): benf\neo\elements\Block::gqlTypeNameByContext(Object(benf\neo\models\BlockType))
#2 /app/vendor/spicyweb/craft-neo/src/gql/types/generators/BlockType.php(39): benf\neo\gql\types\generators\BlockType::generateType(Object(benf\neo\models\BlockType))
#3 /app/vendor/spicyweb/craft-neo/src/gql/interfaces/elements/Block.php(44): benf\neo\gql\types\generators\BlockType::generateTypes()
#4 /app/vendor/spicyweb/craft-neo/src/gql/types/elements/Block.php(26): benf\neo\gql\interfaces\elements\Block::getType()
#5 /app/vendor/spicyweb/craft-neo/src/gql/types/generators/BlockType.php(64): benf\neo\gql\types\elements\Block->__construct(Array)
#6 /app/vendor/spicyweb/craft-neo/src/gql/types/generators/BlockType.php(39): benf\neo\gql\types\generators\BlockType::generateType(Object(benf\neo\models\BlockType))
#7 /app/vendor/spicyweb/craft-neo/src/Field.php(1084): benf\neo\gql\types\generators\BlockType::generateTypes(Object(benf\neo\Field))
#8 /app/vendor/craftcms/cms/src/gql/base/Generator.php(47): benf\neo\Field->getContentGqlType()
#9 /app/vendor/craftcms/cms/src/gql/types/generators/EntryType.php(58): craft\gql\base\Generator::getContentFields(Object(craft\models\EntryType))
#10 /app/vendor/craftcms/cms/src/gql/types/generators/EntryType.php(40): craft\gql\types\generators\EntryType::generateType(Object(craft\models\EntryType))
#11 /app/vendor/craftcms/cms/src/gql/interfaces/elements/Entry.php(54): craft\gql\types\generators\EntryType::generateTypes()
#12 /app/vendor/craftcms/cms/src/gql/queries/Entry.php(40): craft\gql\interfaces\elements\Entry::getType()
#13 /app/vendor/craftcms/cms/src/services/Gql.php(1331): craft\gql\queries\Entry::getQueries()
#14 /app/vendor/craftcms/cms/src/services/Gql.php(366): craft\services\Gql->_registerGqlQueries()
#15 /app/vendor/craftcms/cms/src/services/Gql.php(500): craft\services\Gql->getSchemaDef(Object(craft\models\GqlSchema), true)
#16 /app/vendor/craftcms/cms/src/controllers/GraphqlController.php(177): craft\services\Gql->executeQuery(Object(craft\models\GqlSchema), 'fragment Button...', Array, 'OrderFlowStepsQ...', true)
#17 [internal function]: craft\controllers\GraphqlController->actionApi()
#18 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#20 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('api', Array)
#21 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('graphql/api', Array)
#22 /app/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('graphql/api', Array)
#23 /app/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /app/web/index.php(26): yii\base\Application->run()
#26 {main} {"memory":18089472,"exception":"[object] (TypeError(code: 0): Cannot assign craft\\fields\\PlainText to property benf\\neo\\models\\BlockType::$_field of type ?benf\\neo\\Field at /app/vendor/spicyweb/craft-neo/src/models/BlockType.php:235)"}
```

#### Steps to reproduce
1. have a working multi site on craft 3.5 with NEO plugin and graphQL api working perfectly
2. Upgrade to craft 3.5 to craft 4.0 and spicyweb/craft-neo from 2.13.15 to 3.5.2
3. run any graphql query and you will get the error
> > Cannot assign craft\\fields\\PlainText to property benf\\neo\\models\\BlockType::$_field of type ?benf\\neo\\Field
4. Although the graphql query fails, the CMS including the NEO fields keeps working fine

#### Other information
- Neo version: 3.5.2
- Craft version: Craft Pro 4.3.3
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used? no?

**Comment by ttempleton** [comment]
Thanks for reporting this - it turned out this error occurred if a field that was previously a Neo field had been changed to a different field type. Fixed now in Neo 3.5.3.
