### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by aleksei-kadeikin** [spicywebau/craft-neo#683]
#### Description
Hello!
After we upgraded to version `3.5.9`, we are getting error, which started appearing only on `3.5.9`:
```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'structureId' in where clause is ambiguous in /app/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute(NULL)
#2 /app/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /app/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /app/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->all(NULL)
#5 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1492): craft\db\Query->all(NULL)
#6 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(248): craft\elements\db\ElementQuery->all(NULL)
#7 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(538): benf\neo\elements\db\BlockQuery->benf\neo\elements\db\{closure}()
#8 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(248): benf\neo\elements\db\BlockQuery->_setFilteredResultIfUsingMemoized(Object(Closure))
#9 /app/vendor/spicyweb/craft-neo/src/services/Fields.php(769): benf\neo\elements\db\BlockQuery->all()
#10 /app/vendor/spicyweb/craft-neo/src/Field.php(940): benf\neo\services\Fields->mergeCanonicalChanges(Object(benf\neo\Field), Object(craft\elements\Entry))
#11 /app/vendor/craftcms/cms/src/base/Element.php(4747): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), false)
#12 /app/vendor/craftcms/cms/src/elements/Entry.php(2003): craft\base\Element->afterPropagate(false)
#13 /app/vendor/craftcms/cms/src/services/Elements.php(1104): craft\elements\Entry->afterPropagate(false)
#14 [internal function]: craft\services\Elements->craft\services\{closure}(Object(craft\db\Connection))
#15 /app/vendor/yiisoft/yii2/db/Connection.php(818): call_user_func(Object(Closure), Object(craft\db\Connection))
#16 /app/vendor/craftcms/cms/src/services/Elements.php(1105): yii\db\Connection->transaction(Object(Closure))
#17 /app/vendor/craftcms/cms/src/controllers/ElementsController.php(266): craft\services\Elements->mergeCanonicalChanges(Object(craft\elements\Entry))
#18 [internal function]: craft\controllers\ElementsController->actionEdit(Object(craft\elements\Entry), 9829991)
#19 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit', Array)
#22 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/edit', Array)
#23 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('elements/edit', Array)
#24 /app/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#25 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /app/web/index.php(18): yii\base\Application->run()
#27 {main}
```
Appeared only after an upgrade, so we are kinda sure, that it is related to upgrading to `3.5.9`.

#### Steps to reproduce
We are not sure how it is appearing, but probably by just navigating through the panel and entering some entries.

#### Other information
- Neo version: 3.5.9
- Craft version: Craft Pro 4.3.4

Before we had this problem: https://github.com/spicywebau/craft-neo/issues/682

**Comment by ttempleton** [comment]
This was fixed yesterday in 3.5.9

**Comment by aleksei-kadeikin** [comment]
Hey, @ttempleton!
Tried with `3.x-dev as 3.5.10`, working now. Seems like good to go!

**Comment by ttempleton** [comment]
Thanks for confirming that @aleksei-kadeikin!

Neo 3.5.11 has just been released including the fix for this issue.
