### ISSUE TITLE
PDOException: SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by aleksei-kadeikin** [spicywebau/craft-neo#686]
#### Description
One of our users receives a `Server Error` when trying to open an entry, only entries, where `craft-neo` is being used.
It is not related to access rights or when the user has been created.

Log:
```PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'structureId' in where clause is ambiguous in /app/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute(NULL)
#2 /app/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /app/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /app/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->all(NULL)
#5 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1492): craft\db\Query->all(NULL)
#6 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(248): craft\elements\db\ElementQuery->all(NULL)
#7 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(538): benf\neo\elements\db\BlockQuery->benf\neo\elements\db\{closure}()
#8 /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php(248): benf\neo\elements\db\BlockQuery->_setFilteredResultIfUsingMemoized(Object(Closure))
#9 /app/vendor/spicyweb/craft-neo/src/services/Fields.php(769): benf\neo\elements\db\BlockQuery->all()
#10 /app/vendor/spicyweb/craft-neo/src/Field.php(940): benf\neo\services\Fields->mergeCanonicalChanges(Object(benf\neo\Field), Object(craft\elements\Entry))
#11 /app/vendor/craftcms/cms/src/base/Element.php(4747): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), false)
#12 /app/vendor/craftcms/cms/src/elements/Entry.php(2003): craft\base\Element->afterPropagate(false)
#13 /app/vendor/craftcms/cms/src/services/Elements.php(1104): craft\elements\Entry->afterPropagate(false)
#14 [internal function]: craft\services\Elements->craft\services\{closure}(Object(craft\db\Connection))
#15 /app/vendor/yiisoft/yii2/db/Connection.php(818): call_user_func(Object(Closure), Object(craft\db\Connection))
#16 /app/vendor/craftcms/cms/src/services/Elements.php(1105): yii\db\Connection->transaction(Object(Closure))
#17 /app/vendor/craftcms/cms/src/controllers/ElementsController.php(266): craft\services\Elements->mergeCanonicalChanges(Object(craft\elements\Entry))
#18 [internal function]: craft\controllers\ElementsController->actionEdit(Object(craft\elements\Entry), 9829991)
#19 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit', Array)
#22 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/edit', Array)
#23 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('elements/edit', Array)
#24 /app/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#25 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /app/web/index.php(18): yii\base\Application->run()
#27 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'structureId' in where clause is ambiguous
The SQL being executed was: SELECT `elements`.`id`, `elements`.`canonicalId`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateLastMerged`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`id` AS `siteSettingsId`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `elements`.`dateDeleted`, `neoblocks`.`fieldId`, `neoblocks`.`primaryOwnerId`, `neoblocks`.`typeId`, `neoblocks_owners`.`ownerId`, `neoblocks_owners`.`sortOrder`, `content`.`id` AS `contentId`, `content`.`field_maxWidth`, `content`.`field_flexRow_maxWidth`, `content`.`field_card_horizontalAlign`, `content`.`field_comparisonTableCell_horizontalAlign`, `content`.`field_alignLeft`, `content`.`field_comparisonTableCell_verticalAlign`, `content`.`field_verticalAlign`, `content`.`field_alt`, `content`.`field_notification_animated`, `content`.`field_animatedOnHover`, `content`.`field_arrowPosition`, `content`.`field_articleAuthor`, `content`.`field_autoplay`, `content`.`field_testimonial_background`, `content`.`field_backgroundColor`, `content`.`field_icon_backgroundColor`, `content`.`field_blockId`, `content`.`field_categoryOrder`, `content`.`field_cite_sawkezfh`, `content`.`field_button_color`, `content`.`field_color`, `content`.`field_icon_color`, `content`.`field_link_color`, `content`.`field_logo_color`, `content`.`field_playButton_color`, `content`.`field_container_padding`, `content`.`field_curve`, `content`.`field_currency`, `content`.`field_darkenBackgroundImage`, `content`.`field_delayTime_gsbfhqeg`, `content`.`field_column_direction`, `content`.`field_comparisonTableCell_direction`, `content`.`field_direction`, `content`.`field_display`, `content`.`field_displayAuthor`, `content`.`field_displayComments`, `content`.`field_displayDate`, `content`.`field_displayReadTime`, `content`.`field_displaySocials`, `content`.`field_unoptimized`, `content`.`field_notToCrowdin_qykbzicl`, `content`.`field_dropdownPlacement`, `content`.`field_trigger`, `content`.`field_excerpt`, `content`.`field_faqBlock`, `content`.`field_featureImageAlt`, `content`.`field_filterCategory_qnpjjjfd`, `content`.`field_filterTraits_zvbqxibg`, `content`.`field_fixedPosition`, `content`.`field_fluid`, `content`.`field_cardMedia_full`, `content`.`field_headerType`, `content`.`field_height`, `content`.`field_heroImageAlt`, `content`.`field_image_horizontalAlignment`, `content`.`field_howtoBlock_bxzenxfp`, `content`.`field_href`, `content`.`field_iconBackground`, `content`.`field_elementId`, `content`.`field_includeOnlyInLocales`, `content`.`field_categoryIntro`, `content`.`field_isStaticLink`, `content`.`field_comparisonTableBlock_label`, `content`.`field_label`, `content`.`field_lang`, `content`.`field_listItem_iconColor_vvvynoaf`, `content`.`field_loop`, `content`.`field_mailingList`, `content`.`field_videoPlayer_mediaId`, `content`.`field_navigationLink_megaMenu`, `content`.`field_checkbox_message`, `content`.`field_message`, `content`.`field_checkbox_messageType`, `content`.`field_mobileHeight`, `content`.`field_mobileWidth`, `content`.`field_avatar_name`, `content`.`field_checkbox_name`, `content`.`field_icon_name`, `content`.`field_testimonialCategory_count`, `content`.`field_offline`, `content`.`field_offset`, `content`.`field_orderInMobile`, `content`.`field_orderInTablet`, `content`.`field_inlineFormInput_placeholder`, `content`.`field_placement`, `content`.`field_playOnHover`, `content`.`field_preview`, `content`.`field_priceTag`, `content`.`field_priority_fwcmwebi`, `content`.`field_rating`, `content`.`field_readTime`, `content`.`field_richText`, `content`.`field_scrollDepth_kfsmitzs`, `content`.`field_showContentTable`, `content`.`field_showOnlyFor`, `content`.`field_showSearch_zrtupwki`, `content`.`field_icon_size`, `content`.`field_logo_size`, `content`.`field_pill_size_ojphzzoq`, `content`.`field_size`, `content`.`field_price_smallInMobile`, `content`.`field_videoPlayer_source`, `content`.`field_staticDimensions`, `content`.`field_horizontalNavigation_subBrand_pizytvvp`, `content`.`field_subBrand`, `content`.`field_horizontalNavigation_subBrandLink_swiynzui`, `content`.`field_target`, `content`.`field_separator_text`, `content`.`field_card_theme`, `content`.`field_chart_theme_egruoimh`, `content`.`field_checkbox_theme`, `content`.`field_comparisonTable_theme`, `content`.`field_ctaBlock_theme`, `content`.`field_note_theme_jltijwsn`, `content`.`field_testimonial_theme`, `content`.`field_theme`, `content`.`field_trackingKey`, `content`.`field_translations`, `content`.`field_button_type`, `content`.`field_chart_type_cbxdjqqd`, `content`.`field_inlineFormInput_type`, `content`.`field_inlineForm_type`, `content`.`field_testimonial_type`, `content`.`field_videoCover_type`, `content`.`field_urlCategory`, `content`.`field_useArticleList`, `content`.`field_price_value`, `content`.`field_text_value`, `content`.`field_pill_variant_lpdhrgdh`, `content`.`field_variant`, `content`.`field_className`, `content`.`field_button_width`, `content`.`field_container_width`, `content`.`field_width`, `content`.`field_zapId`, `structureelements`.`root`, `structureelements`.`lft`, `structureelements`.`rgt`, `structureelements`.`level`, `structureelements`.`structureId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId`
FROM `elements` `elements`
INNER JOIN `neoblocks` `neoblocks` ON `neoblocks`.`id` = `elements`.`id`
INNER JOIN `neoblocks_owners` `neoblocks_owners` ON (`neoblocks_owners`.`blockId` = `elements`.`id`) AND (`neoblocks_owners`.`ownerId` = `neoblocks`.`primaryOwnerId`)
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT *
FROM `structures` use index(primary)
WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL)))
INNER JOIN `neoblockstructures` `neoblockstructures` ON `neoblockstructures`.`structureId` = `structureelements`.`structureId`
WHERE (`neoblocks`.`fieldId`=63) AND (`neoblocks`.`primaryOwnerId`=10983003) AND (NOT (`structureId` IS NULL)) AND (`elements_sites`.`siteId`=9) AND (`elements`.`archived`=FALSE) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) AND (`neoblockstructures`.`fieldId`=63) AND (`neoblockstructures`.`siteId`=9)
ORDER BY `structureelements`.`lft`, `neoblocks_owners`.`sortOrder`) `subquery`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `neoblocks` `neoblocks` ON `neoblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `neoblocks_owners` `neoblocks_owners` ON (`neoblocks_owners`.`blockId` = `elements`.`id`) AND (`neoblocks_owners`.`ownerId` = `neoblocks`.`primaryOwnerId`)
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`)
ORDER BY `structureelements`.`lft`, `neoblocks_owners`.`sortOrder` in /app/vendor/yiisoft/yii2/db/Schema.php:676
```

#### Other information
- Neo version: 3.8.10
- Craft version: Craft Pro 4.3.4

**Comment by ttempleton** [comment]
@aleksei-kadeikin in future could you please leave a new comment in issues like #683, rather than editing existing posts or creating duplicate issues, as I do not get notified of edits :)
