### ISSUE TITLE
Update to 3.6.2 fails if no NEO fields exist

### ISSUE THREAD

**Issue by cloudgrayau** [spicywebau/craft-neo#707]
### Bug Description

If Neo is installed, but no NEO fields exist (or a NEO field is created with no block types), the migration fails as following:

```
Output:
================
Checking for pending Craft and plugin migrations ...
Total 1 new Neo migration to be applied:
    - m230202_000653_convert_project_config_icon_data

*** applying m230202_000653_convert_project_config_icon_data
Exception: foreach() argument must be of type array|object, null given (/Users/cloudgray/Sites/cloudgray/vendor/spicyweb/craft-neo/src/migrations/m230202_000653_convert_project_config_icon_data.php:25)
#0 /Users/cloudgray/Sites/cloudgray/vendor/spicyweb/craft-neo/src/migrations/m230202_000653_convert_project_config_icon_data.php(25): yii\base\ErrorHandler->handleError(2, 'foreach() argum...', '/Users/cloudgra...', 25)
#1 /Users/cloudgray/Sites/cloudgray/vendor/craftcms/cms/src/db/Migration.php(49): benf\neo\migrations\m230202_000653_convert_project_config_icon_data->safeUp()
#2 /Users/cloudgray/Sites/cloudgray/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#3 /Users/cloudgray/Sites/cloudgray/vendor/craftcms/cms/src/console/controllers/MigrateController.php(360): yii\console\controllers\BaseMigrateController->migrateUp('m230202_000653_...')
#4 [internal function]: craft\console\controllers\MigrateController->actionAll()
#5 /Users/cloudgray/Sites/cloudgray/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /Users/cloudgray/Sites/cloudgray/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#7 /Users/cloudgray/Sites/cloudgray/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#8 /Users/cloudgray/Sites/cloudgray/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#9 /Users/cloudgray/Sites/cloudgray/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#10 /Users/cloudgray/Sites/cloudgray/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#11 /Users/cloudgray/Sites/cloudgray/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#12 /Users/cloudgray/Sites/cloudgray/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#13 /Users/cloudgray/Sites/cloudgray/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#14 /Users/cloudgray/Sites/cloudgray/craft(13): yii\base\Application->run()
#15 {main}
*** failed to apply m230202_000653_convert_project_config_icon_data (time: 0.017s)


0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.
```

### Steps to reproduce

As above.

### Neo version

3.6.1

### Craft CMS version

Craft Pro 4.3.7

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting - this will be fixed in the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.6.2` and running `composer update`.

**Comment by ttempleton** [comment]
Just released Neo 3.6.3 with that fix.
