### ISSUE TITLE
Cannot Delete Blocks

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#809]
### Bug Description

I am seeing an issue where blocks don't delete when you click the delete block button. I'm seeing the following javascript error in the console:

Block.js:477 Uncaught TypeError: Cannot read properties of undefined (reading 'remove')
    at s.constructor.destroy (Block.js:477:18)
    at s.constructor.removeBlock (Input.js:430:11)
    at s.constructor.removeBlock (Input.js:398:12)
    at Object.handler (Input.js:444:14)
    at s.constructor.trigger (Base.js:83:17)
    at @settingSelect (Block.js:1328:16)
    at s.constructor._handleActionClick (Block.js:1246:10)
    at s.constructor.<anonymous> (Base.js:153:23)
    at HTMLAnchorElement.o (jquery.js?v=1698019876:2:89408)
    at HTMLAnchorElement.dispatch (jquery.js?v=1698019876:2:43392)

### Steps to reproduce

1. Try to delete a block from the gear menu

### Expected behaviour

The block should b removed but it isn't. 

### Neo version

3.9.6

### Craft CMS version

4.5.8

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by brianrivet-tilt** [comment]
You can possibly close this. It seemed to resolve itself after saving the entry and trying again.

**Comment by ttempleton** [comment]
That was an actual bug which I noticed a few days ago while looking into a different bug 😅

It's fixed (see https://github.com/spicywebau/craft-neo/commit/8f00bf3dfe997b80ed644c13fb21a16e731b308d) for release 3.9.7 which will happen in the next few minutes.
