### ISSUE TITLE
Can't apply new propagation method to Neo blocks

### ISSUE THREAD

**Issue by roelvanhintum** [spicywebau/craft-neo#860]
### Bug Description

The queue task for changing the propagation method of a Neo blocks fails.

Error log:
```
2024-03-05 11:06:07 [queue.ERROR] [craft\queue\QueueLogBehavior::afterError]  [17356] t9n:["neo","Applying new propagation method to Neo blocks"] (attempt: 1, pid: 36) - Error (time: 0.009s): Typed property benf\neo\jobs\ApplyNeoPropagationMethod::$structureData must not be accessed before initialization {"memory":33099976} 
2024-03-05 11:06:07 [queue.ERROR] [Error] Error: Typed property benf\neo\jobs\ApplyNeoPropagationMethod::$structureData must not be accessed before initialization in /app/vendor/spicyweb/craft-neo/src/jobs/ApplyNeoPropagationMethod.php:97
Stack trace:
#0 /app/vendor/yiisoft/yii2-queue/src/Queue.php(243): benf\neo\jobs\ApplyNeoPropagationMethod->execute(Object(craft\queue\Queue))
#1 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage(17356, 'O:39:"benf\\neo\\...', 300, 1)
#2 /app/vendor/craftcms/cms/src/queue/Queue.php(191): yii\queue\cli\Queue->handleMessage(17356, 'O:39:"benf\\neo\\...', 300, 1)
#3 /app/vendor/craftcms/cms/src/queue/Queue.php(166): craft\queue\Queue->executeJob()
#4 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#5 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(114): call_user_func(Object(Closure), Object(Closure))
#6 /app/vendor/craftcms/cms/src/queue/Queue.php(164): yii\queue\cli\Queue->runWorker(Object(Closure))
#7 /app/vendor/craftcms/cms/src/controllers/QueueController.php(82): craft\queue\Queue->run()
#8 /app/vendor/craftcms/cms/src/controllers/QueueController.php(103): craft\controllers\QueueController->actionRun()
#9 [internal function]: craft\controllers\QueueController->actionRetry()
#10 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('retry', Array)
#13 /app/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('queue/retry', Array)
#14 /app/vendor/craftcms/cms/src/web/Application.php(642): craft\web\Application->runAction('queue/retry', Array)
#15 /app/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /app/web/index.php(13): yii\base\Application->run()
#18 {main} {"memory":33100192,"exception":"[object] (Error(code: 0): Typed property benf\\neo\\jobs\\ApplyNeoPropagationMethod::$structureData must not be accessed before initialization at /app/vendor/spicyweb/craft-neo/src/jobs/ApplyNeoPropagationMethod.php:97)"} 
2024-03-05 11:06:07 [queue.ERROR] [Error] Error: Typed property benf\neo\jobs\ApplyNeoPropagationMethod::$structureData must not be accessed before initialization in /app/vendor/spicyweb/craft-neo/src/jobs/ApplyNeoPropagationMethod.php:97
Stack trace:
#0 /app/vendor/yiisoft/yii2-queue/src/Queue.php(243): benf\neo\jobs\ApplyNeoPropagationMethod->execute(Object(craft\queue\Queue))
#1 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage(17356, 'O:39:"benf\\neo\\...', 300, 1)
#2 /app/vendor/craftcms/cms/src/queue/Queue.php(191): yii\queue\cli\Queue->handleMessage(17356, 'O:39:"benf\\neo\\...', 300, 1)
#3 /app/vendor/craftcms/cms/src/queue/Queue.php(166): craft\queue\Queue->executeJob()
#4 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#5 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(114): call_user_func(Object(Closure), Object(Closure))
#6 /app/vendor/craftcms/cms/src/queue/Queue.php(164): yii\queue\cli\Queue->runWorker(Object(Closure))
#7 /app/vendor/craftcms/cms/src/controllers/QueueController.php(82): craft\queue\Queue->run()
#8 /app/vendor/craftcms/cms/src/controllers/QueueController.php(103): craft\controllers\QueueController->actionRun()
#9 [internal function]: craft\controllers\QueueController->actionRetry()
#10 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('retry', Array)
#13 /app/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('queue/retry', Array)
#14 /app/vendor/craftcms/cms/src/web/Application.php(642): craft\web\Application->runAction('queue/retry', Array)
#15 /app/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /app/web/index.php(13): yii\base\Application->run()
#18 {main} {"memory":33101536,"exception":"[object] (Error(code: 0): Typed property benf\\neo\\jobs\\ApplyNeoPropagationMethod::$structureData must not be accessed before initialization at /app/vendor/spicyweb/craft-neo/src/jobs/ApplyNeoPropagationMethod.php:97)"} 
```

### Steps to reproduce

1. Create a new Neo field with one block and the `propagationMethod` set to `all` and save the field
2. Change the `propagationMethod` to `siteGroup` and save the field
3. See the queue task/error log

### Expected behaviour

I would expect the queue task to complete without errors.

### Neo version

4.0.6

### Craft CMS version

Craft Pro 4.8.0

### What is the affected Neo field's propagation method?

siteGroup

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed for the next release.
