### ISSUE TITLE
[5.x] Invalid field handle error when switching from an entry type with Neo field(s) to one without

### ISSUE THREAD

**Issue by ch-turnstyle** [spicywebau/craft-neo#920]
### Bug Description

If I create a new entry in the control panel that has any Neo fields, then switch to an entry type that does not have any Neo fields, I get a server error. It should be noted though, that it does not prevent me from creating said new entry.

Stack trace:
```
2024-08-02 09:47:32 [web.ERROR] [craft\errors\InvalidFieldException] craft\errors\InvalidFieldException: Invalid field handle: hero in /var/www/html/vendor/craftcms/cms/src/base/Element.php:5962
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/base/Element.php(4677): craft\base\Element->normalizeFieldValue('hero')
#1 /var/www/html/vendor/spicyweb/craft-neo/src/controllers/Input.php(257): craft\base\Element->getFieldValue('hero')
#2 [internal function]: benf\neo\controllers\Input->actionUpdateVisibleElements()
#3 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('update-visible-...', Array)
#6 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('neo/input/updat...', Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(650): craft\web\Application->runAction('neo/input/updat...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/html/web/index.php(12): yii\base\Application->run()
#11 {main} {"memory":3296568,"exception":"[object] (craft\\errors\\InvalidFieldException(code: 0): Invalid field handle: hero at /var/www/html/vendor/craftcms/cms/src/base/Element.php:5962)"} 
2024-08-02 09:47:32 [web.INFO] [application] Request context:
$_GET = [
    'p' => 'admin/actions/neo/input/update-visible-elements'
    'v' => '1722617252344'
]
```

### Steps to reproduce

1. In the control panel, create a new entry that defaults to an entry type that contains Neo field(s).
2. Via the Entry type dropdown, switch to an entry type that does not have those Neo fields.
3. Server error alert appears.

### Expected behaviour

No server error notice should appear when switching entry types from one with Neo field(s) to one without those Neo fields(s).

### Neo version

5.0.5

### Craft CMS version

5.2.8

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 4.2.10 and 5.1.4.
