### ISSUE TITLE
Invalid field layout element UUID when converting to Craft matrix

### ISSUE THREAD

**Issue by nikistohler** [spicywebau/craft-neo#923]
### Bug Description

I want to convert two of my Neo fields to Craft matrix.
The first one was converted wonderfully.
For the other field I keep getting errors "Invalid something" no matter what I try:
`Invalid field layout element UUID: 496ff55c-36e2-4a86-a45a-5f039ef990f3`

I tried to narrow down if a particular block causes the issue, to no avail.
Neo does create the entryType yaml files for all but one block. However, when I add those entry types to the newly converted matrix all content is gone.

Edit: It's also not working with craft 4 (4.8.9)

**Edit 2: I managed to narrow it down to 2 blocks out of the 10.**
The first one causes the Invalid field layout element UUID error. It's a heading UI element with a condition:
![image](https://github.com/user-attachments/assets/d34f91ad-321d-4d13-a278-dc8ffd158876)

The second one is very confusing however. It's a block (teamBlock) with no fields. And it causes the error:
`Undefined array key "fieldOfActivity"`
The only connection of this fieldOfActivity to the neo field is that it's used in the field layout of the employee channel section. And one of the other blocks, the personBlock, has a entry type field for employee entries.
The neo->matrix conversion works completely fine as long without the teamBlock. If I leave it in, despite it not having any fields, the personBlock causes this error.

### Steps to reproduce

Convert a neo matrix to a craft native matrix

### Expected behaviour

Neo field is converted to matrix and content is preserved.

### Neo version

5.2.0

### Craft CMS version

5.3.2

### What is the affected Neo field's propagation method?

tried both: "Save entries in all sites where the corresponding element is saved" and "Save entries only on the site it was created on".

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by leevigraham** [comment]
I had a similar issue while trying to `convert-to-entry-type` 

```sh
~/Sites/craft-boilerplate.localhost git:[codeception]
ddev craft neo/block-types/convert-to-entry-type --handle=LinkList
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
Exception 'yii\base\InvalidConfigException' with message 'Invalid field layout element UUID: 21f568c7-7073-411a-8104-ec4b65ab3c75'

in /var/www/html/vendor/spicyweb/craft-neo/src/elements/conditions/fields/ParentFieldConditionRuleTrait.php:121

Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/fields/conditions/FieldConditionRuleTrait.php(197): benf\neo\elements\conditions\fields\ParentLightswitchFieldConditionRule->fieldInstances()
#1 /var/www/html/vendor/craftcms/cms/src/elements/conditions/ElementCondition.php(150): craft\fields\conditions\LightswitchFieldConditionRule->getExclusiveQueryParams()
#2 /var/www/html/vendor/craftcms/cms/src/base/conditions/BaseCondition.php(135): craft\elements\conditions\ElementCondition->isConditionRuleSelectable(Object(benf\neo\elements\conditions\fields\ParentLightswitchFieldConditionRule))
#3 [internal function]: craft\base\conditions\BaseCondition->craft\base\conditions\{closure}(Object(benf\neo\elements\conditions\fields\ParentLightswitchFieldConditionRule), '{"class":"benf\\...')
#4 /var/www/html/vendor/illuminate/collections/Arr.php(911): array_filter(Array, Object(Closure), 1)
#5 /var/www/html/vendor/illuminate/collections/Collection.php(388): Illuminate\Support\Arr::where(Array, Object(Closure))
#6 /var/www/html/vendor/craftcms/cms/src/base/conditions/BaseCondition.php(135): Illuminate\Support\Collection->filter(Object(Closure))
#7 /var/www/html/vendor/craftcms/cms/src/base/conditions/BaseCondition.php(242): craft\base\conditions\BaseCondition->getSelectableConditionRules()
#8 /var/www/html/vendor/craftcms/cms/src/base/conditions/BaseCondition.php(201): craft\base\conditions\BaseCondition->validateConditionRule(Object(craft\fields\conditions\LightswitchFieldConditionRule))
#9 /var/www/html/vendor/yiisoft/yii2/base/Component.php(180): craft\base\conditions\BaseCondition->setConditionRules(Array)
#10 /var/www/html/vendor/craftcms/cms/src/helpers/App.php(1465): yii\base\Component->__set('conditionRules', Array)
#11 /var/www/html/vendor/craftcms/cms/src/base/Model.php(84): craft\helpers\App::configure(Object(benf\neo\elements\conditions\BlockCondition), Array)
#12 /var/www/html/vendor/craftcms/cms/src/elements/conditions/ElementCondition.php(85): craft\base\Model->__construct(Array)
#13 [internal function]: craft\elements\conditions\ElementCondition->__construct('benf\\neo\\elemen...', Array)
#14 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#15 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('benf\\neo\\elemen...', Array, Array)
#16 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('benf\\neo\\elemen...', Array, Array)
#17 /var/www/html/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject(Array, Array)
#18 /var/www/html/vendor/craftcms/cms/src/services/Conditions.php(66): Craft::createObject(Array)
#19 /var/www/html/vendor/craftcms/cms/src/base/FieldLayoutComponent.php(215): craft\services\Conditions->createCondition(Array)
#20 /var/www/html/vendor/craftcms/cms/src/base/FieldLayoutComponent.php(186): craft\base\FieldLayoutComponent->_normalizeCondition(Array)
#21 /var/www/html/vendor/craftcms/cms/src/base/FieldLayoutComponent.php(234): craft\base\FieldLayoutComponent->getElementCondition()
#22 /var/www/html/vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\base\FieldLayoutComponent->craft\base\{closure}(Object(craft\fieldlayoutelements\CustomField), 'elementConditio...')
#23 /var/www/html/vendor/craftcms/cms/src/models/FieldLayoutTab.php(218): yii\base\Model->toArray()
#24 /var/www/html/vendor/craftcms/cms/src/models/FieldLayoutTab.php(201): craft\models\FieldLayoutTab->getElementConfigs()
#25 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(541): craft\models\FieldLayoutTab->getConfig()
#26 [internal function]: craft\models\FieldLayout->craft\models\{closure}(Object(craft\models\FieldLayoutTab))
#27 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(540): array_map(Object(Closure), Array)
#28 /var/www/html/vendor/craftcms/cms/src/models/EntryType.php(377): craft\models\FieldLayout->getConfig()
#29 /var/www/html/vendor/craftcms/cms/src/services/Entries.php(1366): craft\models\EntryType->getConfig()
#30 /var/www/html/vendor/spicyweb/craft-neo/src/console/controllers/BlockTypesController.php(409): craft\services\Entries->saveEntryType(Object(craft\models\EntryType))
#31 [internal function]: benf\neo\console\controllers\BlockTypesController->actionConvertToEntryType()
#32 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#33 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#34 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('convert-to-entr...', Array)
#35 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('convert-to-entr...', Array)
#36 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('convert-to-entr...', Array)
#37 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('convert-to-entr...', Array)
#38 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('neo/block-types...', Array)
#39 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('neo/block-types...', Array)
#40 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('neo/block-types...', Array)
#41 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#42 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#43 /var/www/html/craft(13): yii\base\Application->run()
#44 {main}
Failed to run craft neo/block-types/convert-to-entry-type --handle=LinkList: exit status 1
```

**Comment by leevigraham** [comment]
> The first one causes the Invalid field layout element UUID error. It's a heading UI element with a condition:

"with a condition"… that's the thing that causes an error on all my blocks.

**Comment by ttempleton** [comment]
Yeah, condition rules seem to be causing it. I have some incomplete work on fixing it (i.e. the error no longer occurs but the condition rules are lost). My time's been taken up a bit with other projects this week, unfortunately, but I'm definitely aware of this issue, and hoping to have a full fix released next week.

**Comment by ttempleton** [comment]
Fixed for the next release, which will be early next week. In the meantime, you can get the fix by changing your composer.json file's `spicyweb/craft-neo` requirement to `5.x-dev as 5.2.2` and running `composer update`.

**Comment by ttempleton** [comment]
Neo 5.2.3 now released.
