### ISSUE TITLE
Craft 5 upgrade owners table migration failed

### ISSUE THREAD

**Issue by ttempleton** [spicywebau/craft-neo#955]
> @nnuyit That could possibly be a similar issue to [craftcms/cms#14839 (comment)](https://github.com/craftcms/cms/issues/14839#issuecomment-2107254109)? Try running the following SQL query before upgrading:
> 
> ```sql
> DELETE FROM craft_neoblocks WHERE id NOT IN (SELECT id FROM craft_elements);
> ```
> 
> And let me know if that resolves your issue.

It's still not working.
```
    > execute SQL: INSERT INTO {{%elements_owners}}
SELECT * FROM {{%neoblocks_owners}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db`.`craft_elements_owners`, CONSTRAINT `craft_fk_enrxmuymeoripqbbaydmqzjdktcfhdeaakzh` FOREIGN KEY (`ownerId`) REFERENCES `craft_elements` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `craft_elements_owners`
SELECT * FROM `craft_neoblocks_owners` (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `cr...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
#3 /var/www/html/vendor/spicyweb/craft-neo/src/migrations/m240224_024030_migrate_owners_table.php(18): yii\db\Migration->execute('INSERT INTO {{%...')
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): benf\neo\migrations\m240224_024030_migrate_owners_table->safeUp()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp('m240224_024030_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#11 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('migrate/all', Array)
#17 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(60): craft\console\Controller->run('migrate/all', Array)
#18 [internal function]: craft\console\controllers\UpController->actionIndex()
#19 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#22 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('', Array)
#23 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#24 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#25 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#26 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#27 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#28 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#29 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#30 /var/www/html/craft(23): yii\base\Application->run()
#31 {main}
*** failed to apply m240224_024030_migrate_owners_table (time: 0.007s)

```

_Originally posted by @nnuyit in https://github.com/spicywebau/craft-neo/issues/949#issuecomment-2425586573_

**Comment by ttempleton** [comment]
@nnuyit If possible, could you please send in your composer.json/lock and database backup to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by nnuyit** [comment]
> @nnuyit If possible, could you please send in your composer.json/lock and database backup to [plugins@spicyweb.com.au](mailto:plugins@spicyweb.com.au) and we'll have a look at it.

Unfortunately, because of our company policies, we only can send you our composer.json/lock and project config files.
After look up your tables and query. We try this command:

`DELETE FROM craft_neoblocks_owners WHERE ownerId NOT IN (SELECT id FROM craft_elements);`

The migration is success. Can you confirm this one is correct?

**Comment by ttempleton** [comment]
Yeah, I'm happy with that. Glad you've figured out the problem!

We have some garbage collection code that clears out `neoblocks_owners` rows where the Neo blocks don't exist anymore, but we aren't checking for owners that don't exist anymore, so I'll add that in the next 4.x release.
