### ISSUE TITLE
craft v4 to v5 migration: Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.neoblocks_owners' doesn't exist

### ISSUE THREAD

**Issue by joepagan** [spicywebau/craft-neo#968]
### Bug Description

Try run migration, get migration error:

```
*** applying m231112_170900_FixNeoOwnersBeforeMigration
    > execute SQL:
            DELETE no FROM {{%neoblocks_owners}} no
            LEFT JOIN {{%elements}} e ON no.ownerId = e.id
            WHERE e.id IS NULL
         ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.neoblocks_owners' doesn't exist
The SQL being executed was:
            DELETE no FROM `neoblocks_owners` no
            LEFT JOIN `elements` e ON no.ownerId = e.id
            WHERE e.id IS NULL
         (/var/www/html/cms/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/cms/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), '\n            DE...')
#1 /var/www/html/cms/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('\n            DE...')
#2 /var/www/html/cms/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
#3 /var/www/html/cms/migrations/m231112_170900_FixNeoOwnersBeforeMigration.php(13): yii\db\Migration->execute('\n            DE...')
#4 /var/www/html/cms/vendor/craftcms/cms/src/db/Migration.php(50): craft\contentmigrations\m231112_170900_FixNeoOwnersBeforeMigration->safeUp()
#5 /var/www/html/cms/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/html/cms/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp('m231112_170900_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/html/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/cms/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#11 /var/www/html/cms/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction('all', Array)
#12 /var/www/html/cms/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#13 /var/www/html/cms/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /var/www/html/cms/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/cms/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/cms/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /var/www/html/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#18 /var/www/html/cms/craft(13): yii\base\Application->run()
#19 {main}
*** failed to apply m231112_170900_FixNeoOwnersBeforeMigration (time: 0.001s)


49 from 50 migrations were applied.

Migration failed. The rest of the migrations are canceled.

Restore a database backup before trying again.
Failed to run craft migrate/all: exit status 1
```

### Steps to reproduce

- ensure current database/project is on `"craftcms/cms": "4.12.8",` with `"spicyweb/craft-neo": "4.2.19",`
- craft gc/run
- change to v5 git branch with `"craftcms/cms": "5.5.0.1",` and `"spicyweb/craft-neo": "5.2.15",`
- composer install
- run SQL query `DELETE FROM neoblocks WHERE id NOT IN (SELECT id FROM elements);` to overcome #949 
- craft migrate/all
- get migration error

### Expected behaviour

all migrations to succeed

### Neo version

5.2.15

### Craft CMS version

5.5.0.1

### What is the affected Neo field's propagation method?

no sure what this is sorry

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
The error is coming from a content migration which is running after your other Craft app and plugin migrations; i.e. after Neo has already removed the `neoblocks_owners` table. If you need to run a content migration related to that table, you will need to do it before upgrading to Craft 5.

**Comment by joepagan** [comment]
Ah thanks for that, didn't see there was a custom migration when reviewing this.
